EPMDJ-3142: Add new "Manage Session" panel
Drill4J/admin-ui pull request #364
Opened 2020-08-31 14:06 UTC by RomanAchilov

Issue: EPMDJ-3142

2020-09-16 08:19 UTC, pavyarov requested changes
I have coupe of questions:
1. Why you managing error messages at frontend?

2020-09-17 10:31 UTC, pavyarov requested changes

2020-09-17 10:31 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +        {abortingSessionIdByAgentId === sessionId + agentId ? (
too much logic, split it to component

2020-09-17 10:31 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +    const disabled = Boolean(abortingSessionIdByAgentId && sessionId + agentId !== abortingSessionIdByAgentId);
`sessionId + agentId !== abortingSessionIdByAgentId` what?

2020-09-17 10:31 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +                    onClick={() => finishSession(agentId, sessionId, pluginId, showGeneralAlertMessage)}
to much arguments

2020-09-17 10:31 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +    const agentType = serviceGroupId ? 'ServiceGroup' : 'agent';
why agent is't capitalized?

2020-09-17 10:31 UTC, pavyarov commented on src/modules/manage-sessions-pane/use-active-sessions.ts
> +export function useActiveSessions<Data>(agentType: string, id: string, buildVersion?: string) {
any reason for generic here?

2020-09-17 10:31 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx
> +      onClick: () => dispatch(openModal('ManageSessionsPane', null)),
so we have panels but this particular case is pane?

2020-09-17 11:55 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +    const disabled = Boolean(abortingSessionIdByAgentId && sessionId + agentId !== abortingSessionIdByAgentId);
I need this to correctly disable sessions in the service group

2020-09-18 08:43 UTC, pavyarov approved these changes

2020-09-18 08:46 UTC, merged