EPMDJ-3030: Add Back button. Add correct data at the first configuration
Drill4J/admin-ui pull request #379
Opened 2020-09-10 12:33 UTC by RomanAchilov

Issue: EPMDJ-3030 EPMDJ-3118 EPMDJ-3345

2020-09-11 19:43 UTC, pavyarov requested changes
Don't like that solution atupdateQualityGateSettings`. So i think we need to refactor this a bit.

2020-11-10 20:24 UTC, RomanAchilov commented on src/components/quality-gate-pane/api/update-quality-gate-settings.ts
> +              value: formValues.coverage.condition.value ? formValues.coverage.condition.value : 0.1,
?
just ||

2020-11-10 20:24 UTC, RomanAchilov commented on src/components/quality-gate-pane/quality-gate-pane.tsx
> +    const initialValues = {
?

2020-11-11 12:24 UTC, RomanAchilov commented on src/modules/quality-gate-pane/quality-gate-pane.tsx
> +          value: conditionSettingByType.coverage?.enabled ? conditionSettingByType.coverage.condition.value : undefined,
?

2020-11-16 08:38 UTC, RomanDavlyatshin requested changes

2020-11-16 08:38 UTC, RomanDavlyatshin commented on src/forms/form-validators.ts
> +    return !isNumeric(get(valitationItem, fieldName) || '') || Number.isNaN(value) || value < min || value > max
Long return statements are hard to read.
I suggest refactoring to a normal `if` clause instead of a ternary operator.

2020-11-16 08:38 UTC, RomanDavlyatshin commented on src/forms/form-validators.ts
> +      ? toError(fieldName, fieldAlias || `${camelToSpaces(fieldName)} should be between ${min} and ${max}.`)
Omg, ok I got that now.
Either rename `fieldAlias` to `errorMessage` or make it an actual **alias**

2020-11-16 08:38 UTC, RomanDavlyatshin commented on src/modules/quality-gate-pane/quality-gate-pane.tsx
> +    fieldAlias: 'Build coverage should be between 0.1 and 100 percentages.',
Why use a string literal with baked-in values?

2020-11-16 08:38 UTC, RomanDavlyatshin commented on src/modules/quality-gate-pane/quality-gate-pane.tsx
> +  formValues.tests?.enabled ? positiveInteger('tests.condition.value', 'Tests to run') : () => undefined,
Can't `'tests.condition.value'` be replaced with `formValues?.risks?.condition?.value`?
That would allow omitting `get('foo.bar.baz')` calls inside validator functions.
Am I missing something?

2020-11-16 08:38 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
> +                      <div>Configure quality gate conditions to</div>
`</br>` ?
Doesn't tooltip has `max-width`?

2020-11-16 08:38 UTC, RomanDavlyatshin commented on src/utils/input-restriction.ts
> +export const inputRestriction = (str: string, maxCharacters: number): string =>
`inputLengthRestriction`

2020-11-16 09:48 UTC, merged