EPMDJ-3322: fix bug with show success or error notification
Drill4J/admin-ui pull request #391
Opened 2020-09-28 15:15 UTC by SMPlay

Issue: EPMDJ-3322

2020-09-28 16:20 UTC, RomanAchilov requested changes
1) check https://jiraeu.epam.com/browse/EPMDJ-3322
2) rebase

2020-09-28 16:20 UTC, RomanAchilov commented on src/pages/agents-page/agents-table/agents-table.tsx
> +  const onChangeAgentStatus = async (agentId: string, status: string) => {
async/await need here?

2020-09-28 16:20 UTC, RomanAchilov commented on src/pages/agents-page/agents-table/agents-table.tsx
> +      (errorMessage: string) => {
` (errorMessage: string) => showMessage({
          type: 'ERROR',
          text: errorMessage || 'There is some issue with your action. Please try again later.',
        })`

2020-09-28 16:20 UTC, RomanAchilov commented on src/pages/agents-page/agents-table/agents-table.tsx
> +              <AgentStatusToggler status={value} onChange={() => toggleAgent(item.id)} />
toggle for service group agents should not work?

2020-09-29 09:03 UTC, RomanAchilov approved these changes

2020-09-29 09:54 UTC, pavyarov requested changes

2020-09-29 09:54 UTC, pavyarov commented on src/pages/settings-page/settings-page.tsx
> +    const onChangeAgentStatus = (agentId: string, status: string) => {
completely copy-paste

2020-09-29 10:00 UTC, SMPlay commented on src/pages/settings-page/settings-page.tsx
> +    const onChangeAgentStatus = (agentId: string, status: string) => {
Should I just remove the handler or add success and error logic to the toggle-agent function?

2020-09-30 09:48 UTC, RomanAchilov approved these changes

2020-10-01 10:14 UTC, pavyarov requested changes

2020-10-01 10:14 UTC, pavyarov commented on src/pages/api/toggle-agent.ts
> +  status: string,
agent `status` is definitely not string

2020-10-01 10:20 UTC, SMPlay commented on src/pages/api/toggle-agent.ts
> +  status: string,
`status` gets a string `ONLINE` or `OFFLINE`

2020-10-01 11:48 UTC, pavyarov approved these changes

2020-10-01 11:48 UTC, merged