EPDDJ-4407: update UI scope action: include/ignore
Drill4J/admin-ui pull request #393
Opened 2020-09-29 15:54 UTC by IliaSolovev

2020-09-30 07:42 UTC, RomanAchilov approved these changes

2020-10-01 10:23 UTC, pavyarov requested changes

2020-10-01 10:23 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
> +        label: enabled ? 'Ignore in stats' : 'Show in stats',
```suggestion
        label: `${enabled ? 'Ignore' : 'Show' in stats`,

```

2020-10-01 10:23 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
> +              } build stats.`,
```
text: `Scope has been ${
  enabled ? 'ignored' : 'included'
} in build stats.`,

```

2020-10-01 10:23 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
> +                  label: item.enabled ? 'Ignore in stats' : 'Show in stats',
```suggestion
                  label: `${enabled ? 'Ignore' : 'Show' in stats`,

```

2020-10-01 10:23 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
> +                        text: `Scope has been ${
text: `Scope has been ${
  enabled ? 'ignored' : 'included'
} in build stats.`,

2020-10-01 10:36 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
> +                  label: item.enabled ? 'Ignore in stats' : 'Show in stats',
I can`t destructure item object because it it passed in other places

2020-10-01 10:45 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
> +                        text: `Scope has been ${
I can`t destructure item object because it it passed in other places

2020-10-01 11:14 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
> +                        text: `Scope has been ${
I can`t destructure item object because it is passed in other places

2020-10-01 11:20 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
> +                        text: `Scope has been ${
const { active, enabled } = item;

2020-10-01 12:20 UTC, pavyarov approved these changes

2020-10-01 12:22 UTC, merged