EPMDJ-3612: Add ability "Offline Agent" preregister
Drill4J/admin-ui pull request #395
Opened 2020-09-30 17:36 UTC by RomanAchilov

Issue: EPMDJ-3612

2020-10-01 08:06 UTC, RomanAchilov commented on src/pages/agents-page/agents-page.tsx
> +  ) || []).filter((offlineAgent) => offlineAgent.instanceIds?.length === 0);
need improvements from BE

2020-10-01 08:06 UTC, RomanAchilov commented on src/pages/agents-page/agents-page.tsx
> +      .map((offlineAgent) => ({ ...offlineAgent, status: 'PREPARED' as AgentStatus })),
need improvements from BE

2020-10-06 13:36 UTC, pavyarov requested changes

2020-10-06 13:36 UTC, pavyarov commented on src/pages/agent-registration-page/agent-registration-page.tsx
> +            : preregisterOfflineAgent(() => {
What the reason to left it there

2020-10-06 13:36 UTC, pavyarov commented on src/pages/agent-registration-page/agent-registration-page.tsx
> +            message={`Are you sure you want to abort ${agentId
Same question

2020-10-07 10:10 UTC, RomanAchilov commented on src/pages/agent-registration-page/agent-registration-page.tsx
> +            : preregisterOfflineAgent(() => {
to avoid passing the agentId below

2020-10-07 10:10 UTC, RomanAchilov commented on src/pages/agent-registration-page/agent-registration-page.tsx
> +            message={`Are you sure you want to abort ${agentId
to avoid passing the agentId below

2020-10-20 12:25 UTC, pavyarov approved these changes

2020-10-20 12:28 UTC, merged