EPMDJ-2880: Add plugin settings tab to service group
Drill4J/admin-ui pull request #405
Opened 2020-10-06 07:34 UTC by IliaSolovev

Issue: EPMDJ-2880 EPMDJ-4810

2020-10-06 08:39 UTC, RomanAchilov requested changes

2020-10-06 08:39 UTC, RomanAchilov commented on src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx
> +  dataId: string;
agentId

2020-10-06 08:39 UTC, RomanAchilov commented on src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx
> +  agentType: 'service-group' | 'agent';
string

2020-10-06 08:39 UTC, RomanAchilov commented on src/modules/plugins-settings-tab/plugins-settings-tab.tsx
> +  data: Agent;
agent

2020-10-06 08:39 UTC, RomanAchilov commented on src/modules/plugins-settings-tab/plugins-settings-tab.tsx
> +    data,
agent: { id: agentId = '', plugins = [], buildVersion },

2020-10-06 08:39 UTC, RomanAchilov commented on src/pages/settings-page/agent-settings/agent-settings.tsx
> +      component: <PluginsSettingsTab data={agent} />,
agent

2020-10-06 08:39 UTC, RomanAchilov commented on src/pages/settings-page/agent-settings/general-settings-form/general-settings-form.module.scss
> +    position: relative;
))

2020-10-06 13:43 UTC, pavyarov requested changes

2020-10-06 13:43 UTC, pavyarov commented on src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx
> +  const connectionUrl = `/${agentType === 'agent' ? 'agents' : 'service-groups'}/${agentId}/plugins`;
This is not url. This is topic

2020-11-16 18:06 UTC, SMPlay commented on src/modules/plugins-settings-tab/no-plugins-stub/no-plugins-stub.tsx
> +  children: string;
maybe can you use `React.ReactNode` and in the future you can give here some content (e.g. `<div>Content</div>`)

2020-11-16 18:06 UTC, SMPlay commented on src/modules/plugins-settings-tab/plugins-settings-tab.module.scss
> +    border-bottom: 1px solid map-get($monochrome, medium-tint);
up

2020-11-16 18:10 UTC, IliaSolovev commented on src/modules/plugins-settings-tab/no-plugins-stub/no-plugins-stub.tsx
> +  children: string;
i  can use it but now it not necessary

2020-11-16 19:21 UTC, RomanAchilov requested changes

2020-11-16 19:21 UTC, RomanAchilov commented on src/modules/plugins-settings-tab/plugins-settings-tab.tsx
> +    const plugins: Plugin[] = useWsConnection<Plugin[]>(defaultAdminSocket, pluginsTopic) || [];
??????

2020-11-16 19:21 UTC, RomanAchilov commented on src/types/plugin.ts
> +  id: string;
?

2020-11-16 21:41 UTC, pavyarov requested changes

2020-11-16 21:41 UTC, pavyarov commented on src/modules/plugins-settings-tab/plugins-settings-tab.module.scss
> +    height: auto;
em?)  `auto` is default value

2020-11-16 21:41 UTC, pavyarov commented on src/modules/plugins-settings-tab/add-plugins-modal/add-plugins-modal.tsx
> +  pluginsTopic: string;
just want to metntion.
Passing topics via props was temprorary solution

2020-11-18 08:01 UTC, RomanAchilov requested changes

2020-11-18 08:08 UTC, merged