EPMDJ-4809: Add data test attributes to UI elements
Drill4J/admin-ui pull request #407
Opened 2020-10-08 05:58 UTC by IliaSolovev

Issue: EPMDJ-4809

2020-10-08 07:22 UTC, RomanAchilov requested changes

2020-10-08 07:22 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +        header={<OverflowText data-test="finish-scope-modal:title">{`Finish Scope ${scope && scope.name}`}</OverflowText>}
data-test="finish-scope-modal:header

2020-10-08 07:22 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +                data-test={`finish-scope-modal:${testsCount ? 'finish' : 'finish-and-delete'}-scope-button`}
just finish-scope-button.
the attribute must be constant

2020-10-08 07:36 UTC, RomanAchilov approved these changes

2020-10-12 09:08 UTC, pavyarov approved these changes

2020-10-12 09:11 UTC, merged