EPMDJ-4837: Update cherts on Agent Dashboard page
Drill4J/admin-ui pull request #408
Opened 2020-10-08 12:05 UTC by SMPlay

Issue: EPMDJ-4837

2020-10-09 14:53 UTC, RomanAchilov requested changes

2020-10-09 14:53 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/dashboard.tsx
> +                label={name?.toUpperCase()}
mb text-transform: uppercase

2020-10-09 14:53 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.module.scss
> +  &__link {
add empty line

2020-10-09 14:53 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/sections/coverage-section/coverage-section.tsx
> +              && (previousBuildVersion !== '' && buildVersion !== previousBuildVersion)
maybe better const isFirstBuild = !previousBuildVersion

2020-10-09 15:14 UTC, RomanAchilov requested changes

2020-10-09 15:14 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/plugin-card/plugin-card.module.scss
>      border-bottom: 1px solid map-get($color-palette, light-blue);
remove outdated styles

2020-10-09 15:21 UTC, RomanAchilov approved these changes

2020-10-12 08:53 UTC, RomanAchilov requested changes

2020-10-12 08:53 UTC, RomanAchilov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.module.scss
> +  &__tooltip-item-total,
?

2020-10-12 09:01 UTC, SMPlay commented on src/components/coverage-section-tooltip/coverage-section-tooltip.module.scss
> +  &__tooltip-item-total,
![Screenshot 2020-10-12 120058](https://user-images.githubusercontent.com/49731235/95727289-a21ca480-0c82-11eb-81e4-70d5dc5fc70e.png)

2020-10-12 09:07 UTC, pavyarov requested changes

2020-10-12 09:07 UTC, pavyarov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.tsx
> +          {label === 'totalCovered'
what is that?

2020-10-12 09:07 UTC, pavyarov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.tsx
> +          {label === 'totalCovered'
Destructuring assignment `totalCovered`, then map rest

2020-10-12 09:09 UTC, RomanAchilov requested changes

2020-10-12 09:09 UTC, RomanAchilov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.module.scss
> +  &__tooltip-item-total,
![image](https://user-images.githubusercontent.com/41574246/95727576-ffb0f100-0c82-11eb-9d9f-9f1776b26498.png)

2020-10-13 09:15 UTC, pavyarov requested changes

2020-10-13 09:15 UTC, pavyarov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.tsx
> +  { className, data: { totalCovered: { covered, total, percent }, ...rest } }: Props,
More convenient name for rest

2020-10-13 09:15 UTC, pavyarov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.tsx
> +    {Object.keys(rest).map((label) => (
This is definitely not a label

2020-10-13 09:15 UTC, pavyarov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.tsx
> +  data: Record<string, { percent?: number; total: number, covered: number }>;
So I pass total and covered, why u still need to calc percent outside?

2020-10-13 09:15 UTC, pavyarov commented on src/pages/agent-full-page/dashboard/sections/tests-section.tsx
> +                data={{
Looks ugly, refactor it

2020-10-13 18:59 UTC, SMPlay commented on src/components/coverage-section-tooltip/coverage-section-tooltip.tsx
> +  data: Record<string, { percent?: number; total: number, covered: number }>;
because the percentages are different with `/build/methods` and `/build/coverage`. I'll resolve it

2020-10-14 14:22 UTC, pavyarov requested changes

2020-10-14 14:22 UTC, pavyarov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.tsx
> +    {Object.keys(coverageDetails).map((coverageDetail) => (
```suggestion
    {Object.keys(coverageDetails).map((testType) => (
```

2020-10-14 14:22 UTC, pavyarov commented on src/pages/agent-full-page/dashboard/sections/tests-section.tsx
> +  const tooltipData = {
This is reduce

2020-10-14 15:25 UTC, SMPlay commented on src/pages/agent-full-page/dashboard/sections/tests-section.tsx
> +  const tooltipData = {
if I'll do reduce, then the tooltip will not have a null value

2020-10-19 10:55 UTC, RomanAchilov approved these changes

2020-10-20 17:49 UTC, RomanAchilov requested changes

2020-10-23 18:19 UTC, IliaSolovev requested changes

2020-10-23 18:19 UTC, IliaSolovev commented on src/pages/agent-full-page/dashboard/sections/section/section.module.scss
>      font-size: 13px;
it`s strange value

2020-10-23 22:24 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/sections/section/section.module.scss
>      font-size: 13px;
incorrect font-size

2020-10-23 23:16 UTC, RomanAchilov requested changes
![image](https://user-images.githubusercontent.com/41574246/97061225-dce5dd00-159e-11eb-9889-5c66b7933fbc.png)

2020-10-27 09:29 UTC, RomanAchilov requested changes

2020-10-27 09:29 UTC, RomanAchilov commented on src/components/coverage-section-tooltip/coverage-section-tooltip.module.scss
> +    opacity: 50%;
0.5

2020-10-27 09:29 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/sections/risks-section/risks-section.module.scss
> +    opacity: 25%;
0.25

2020-10-27 12:03 UTC, RomanAchilov approved these changes

2020-10-27 14:03 UTC, IliaSolovev approved these changes

2020-10-28 10:31 UTC, RomanAchilov approved these changes

2020-10-28 10:36 UTC, IliaSolovev approved these changes

2020-10-31 13:21 UTC, pavyarov requested changes

2020-10-31 13:21 UTC, pavyarov commented on src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx
> +    autoTests: {
auto

2020-10-31 13:21 UTC, pavyarov commented on src/pages/agent-full-page/dashboard/sections/tests-section.tsx
> +    autoTests: {
auto

2020-10-31 13:21 UTC, pavyarov commented on src/types/test-to-run-info.ts
> +export interface TestToRunInfo {
```
export type TestToRunInfo = Record<string, { count: number; }>;
```

2020-10-31 13:28 UTC, SMPlay commented on src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx
> +    autoTests: {
ifI I rename this variable to simple `auto`, then won't converge with the layout
![image](https://user-images.githubusercontent.com/49731235/97780494-1f5a7b80-1b96-11eb-8696-e660a5d0d84e.png)

2020-10-31 13:34 UTC, SMPlay commented on src/pages/agent-full-page/dashboard/sections/tests-section.tsx
> +    autoTests: {
reason above

2020-10-31 20:56 UTC, pavyarov commented on src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx
> +    autoTests: {
So, what about specifications?

2020-11-01 06:38 UTC, SMPlay commented on src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx
> +    autoTests: {
![charts](https://user-images.githubusercontent.com/49731235/97796666-ef5ab900-1c25-11eb-9cd3-ba18689bbde3.png)
in specs

2020-11-03 11:49 UTC, pavyarov approved these changes

2020-11-03 11:50 UTC, merged