EPMDJ-4871: Support ArrowType.UNCHANGED
Drill4J/admin-ui pull request #409
Opened 2020-10-08 12:37 UTC by SMPlay

Issue: EPMDJ-4871

2020-10-08 20:25 UTC, RomanAchilov approved these changes

2020-10-12 08:53 UTC, pavyarov requested changes

2020-10-12 08:53 UTC, pavyarov commented on src/pages/service-group-full-page/dashboard/sections/coverage-section/coverage-section.tsx
> +import { ArrowType } from 'types/arrow-type';
move under utils

2020-10-12 08:53 UTC, pavyarov commented on src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
> +                <TestToCodeCoverageCell value={value} arrow={arrow !== 'UNCHANGED' ? arrow : null} />
why if statement here? not at `TestToCodeCoverageCell`

2020-10-12 09:17 UTC, SMPlay commented on src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
> +                <TestToCodeCoverageCell value={value} arrow={arrow !== 'UNCHANGED' ? arrow : null} />
fixed. I don't know why I wrote such a condition here

2020-10-12 14:00 UTC, pavyarov approved these changes

2020-10-12 14:01 UTC, merged