EPMDJ-4840: Update build/scope test tables
Drill4J/admin-ui pull request #410
Opened 2020-10-08 12:42 UTC by IliaSolovev

Issue: EPMDJ-4840

2020-10-09 16:58 UTC, RomanAchilov requested changes

2020-10-09 16:58 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +              data={testsUsages
testsUsages.map(({ tests = [], testType }) => tests.map((test) => ({ ...test, testType })))

2020-10-09 16:58 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +const StatusCell = testDetails.statusCell(span({} as { type?: 'passed' | 'failed' }));
u can use just "span"

2020-10-09 16:58 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
>  const TableCell = testDetails.tableCell(span({} as { type?: 'primary' | 'secondary' }));
u can use just "span"

2020-10-09 17:09 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.tsx
> +  nameKey: string;
because nameKey can be different in another items.  You can see it on coverage-details and test-details components

2020-10-12 08:49 UTC, pavyarov requested changes

2020-10-12 08:49 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.module.scss
> +@import '~common/style-guide/index';
convert line endings back. rule is off atm

2020-10-12 08:49 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss
> +@import '~common/style-guide/index';
same here

2020-10-12 09:41 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.module.scss
> +@import '~common/style-guide/index';
I`ll try to resolve this problem, but my autocrlf rule off. 
![image](https://user-images.githubusercontent.com/49729985/95731487-41906600-0c88-11eb-862b-04edd653406a.png)

2020-10-16 14:48 UTC, RomanAchilov requested changes

2020-10-16 14:48 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss
> +    color: $slate-gray;
outdated

2020-10-16 14:48 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss
> +    color: $slate-gray;
check design system

2020-10-16 14:48 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss
> +  &__status-cell {
maybe it can be written more compactly ?

2020-10-16 17:44 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss
> +  &__status-cell {
i tried to write it more compactly but i have not ideas how i can do it

2020-10-19 10:48 UTC, RomanAchilov approved these changes

2020-10-19 10:53 UTC, RomanAchilov approved these changes

2020-10-19 12:36 UTC, pavyarov requested changes

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.module.scss
> +    width: 40vw;
why? look at line 17, main idea was this cell should fill all parent size

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.module.scss
> +    width: 40vw;
also i don't even understand why you chose 40% of window? this came from mock-ups?

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.tsx
> +        <ClassPath title={String(path)}>{path || '-'}</ClassPath>
`path || '-'` is that correct for all cases?

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.tsx
> +        <ClassPath title={String(path)}>{path || '-'}</ClassPath>
i mean this is `CompoundCell` kinda generic feature

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.tsx
> +    className, pathKey, nameKey, icon, item: { [nameKey]: name, [pathKey]: path } = {},
add default value for nameKey at least

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.module.scss
> +      font-family: $semibold-font;
why `font-family` at modifier?

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                  <StatusCell type={value !== null && value.result}>
```suggestion
                  <StatusCell type={testStatus?.result}>

```

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                Cell={({ value }) => (
```suggestion
                Cell={({ value: testStatus }) => (

```

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                    {value !== null && capitalize(value.result)}
value !== null? so why only `null`? so if value is `undefined`? its okay?

2020-10-19 12:36 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                    {value === 0 && <CoverageIcon><Icons.Function /></CoverageIcon>}
i can't find a relation if value === 0 then render icon? what?

2020-10-19 12:55 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.tsx
> +    className, pathKey, nameKey, icon, item: { [nameKey]: name, [pathKey]: path } = {},
you mean `nameKey = 'name'` I`m right

2020-10-19 13:03 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                    {value === 0 && <CoverageIcon><Icons.Function /></CoverageIcon>}
If coverage is empty i should show so icon, I also forgot add tooltip here

2020-10-19 13:16 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                    {value !== null && capitalize(value.result)}
I`ll you optional chaining here

2020-10-19 13:19 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/compound-cell/compound-cell.tsx
> +    className, pathKey, nameKey, icon, item: { [nameKey]: name, [pathKey]: path } = {},
Yes

2020-10-19 13:23 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                    {value === 0 && <CoverageIcon><Icons.Function /></CoverageIcon>}
This is wrong icon, look at mock-up more carefully

2020-10-20 07:55 UTC, pavyarov approved these changes

2020-10-20 07:55 UTC, merged