EPMDJ-3644: No alignment in the "All scopes" table header when it is empty
Drill4J/admin-ui pull request #412
Opened 2020-10-08 19:15 UTC by SMPlay

Issue: EPMDJ-3644

2020-10-08 20:00 UTC, RomanAchilov requested changes

2020-10-09 13:28 UTC, RomanAchilov requested changes

2020-10-09 13:28 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.module.scss
> +  height: 80%;
cacl()

2020-10-09 14:21 UTC, RomanAchilov approved these changes

2020-10-09 14:21 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
> +          scopesData.length !== 0
scopesData.length > 0

2020-10-12 08:12 UTC, RomanAchilov approved these changes

2020-10-12 08:12 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/scopes-list/scopes-list.tsx
>            All scopes
Scopes

2020-10-12 08:43 UTC, pavyarov requested changes

2020-10-12 08:43 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.module.scss
> +@import '~common/style-guide/index';
line endings

2020-10-12 08:43 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.tsx
> +      <Icons.Scope width={157} height={157} data-test="no-scope-stub:test-icon" />
the commit message said 'No alignment in the "All scopes" table header when it is empty'. So WTF is this then?

2020-10-12 08:51 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.tsx
> +      <Icons.Scope width={157} height={157} data-test="no-scope-stub:test-icon" />
that was the name of the task in JIRA. Should I change to "add a stub with empty scopes"?

2020-10-12 08:51 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.module.scss
> +@import '~common/style-guide/index';
I can't resolve this

2020-10-12 09:20 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.tsx
> +      <Icons.Scope width={157} height={157} data-test="no-scope-stub:test-icon" />
of course! commit message and PR description !== jira header

2020-10-12 09:23 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.module.scss
> +@import '~common/style-guide/index';
em... What the problem? Turn off `autocrlf`

2020-10-12 09:24 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.module.scss
> +@import '~common/style-guide/index';
Also check husky, husky should format only staged files

2020-10-12 09:32 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/scope/no-scope-stub/no-scope-stub.module.scss
> +@import '~common/style-guide/index';
My autocrlf is off

2020-10-14 14:25 UTC, pavyarov approved these changes

2020-10-19 10:36 UTC, merged