EPMDJ-3753: Update covered methods modal
Drill4J/admin-ui pull request #414
Opened 2020-10-20 12:45 UTC by SMPlay

Issue: EPMDJ-3753

2020-10-20 18:34 UTC, RomanAchilov requested changes
Not matching the layout, we'll look at it together tomorrow

2020-10-20 18:34 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
> -            <Icons.Function height={18} width={18} />
you deleted the icon but didn't delete the import
![image](https://user-images.githubusercontent.com/41574246/96626697-7f405f00-1318-11eb-91e9-aab67c586d70.png)
![image](https://user-images.githubusercontent.com/41574246/96626713-86676d00-1318-11eb-894d-327f0ed2fe29.png)

2020-10-20 18:34 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/covered-methods-by-test-type-sidebar.tsx
> -            <Icons.Function height={18} width={18} />
same

2020-10-22 11:39 UTC, RomanAchilov requested changes
![image](https://user-images.githubusercontent.com/41574246/96866743-6c42a180-1474-11eb-9a90-580d64a1c425.png)
![image](https://user-images.githubusercontent.com/41574246/96866759-72388280-1474-11eb-85af-39406e96dbd2.png)

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/coverage-rate-icon/coverage-rate-icon.module.scss
> +  margin-top: 2px;
😠

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.module.scss
> +    margin-top: 2px;
very strange alignment

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/covered-methods-by-test-type-sidebar.tsx
>              <h2>{allMethods.length}</h2>
fix this
check mockups
it's too bad that I have to double check the styles
![image](https://user-images.githubusercontent.com/41574246/96865695-f4c04280-1472-11eb-8f34-3c47d84079d9.png)
![image](https://user-images.githubusercontent.com/41574246/96865801-191c1f00-1473-11eb-8d01-33afdd8912b1.png)

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.module.scss
>      margin-right: 18px;
fix

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.module.scss
> +    color: map-get($monochrome, default);
lower it

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss
> +    background-color: rgba(map-get($monochrome, light-tint), 0.5);
background-color: map-get($monochrome, light-tint);

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-type-sidebar/covered-methods-by-test-type-sidebar.module.scss
> +    background-color: rgba(map-get($monochrome, light-tint), 0.5);
background-color: map-get($monochrome, light-tint);

2020-10-22 11:39 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> -          <CoveredMethodsByTestTypeSidebar
not used but the component was not deleted

2020-10-22 20:10 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> -          <CoveredMethodsByTestTypeSidebar
this will be fixed in another task

2020-10-23 23:45 UTC, RomanAchilov requested changes

2020-10-23 23:45 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/coverage-rate-icon/coverage-rate-icon.module.scss
> +    height: 16px;
empty line

2020-10-23 23:45 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
> +const MethodsCount = coveredMethodsByTestSidebar.methodsCount('h2');
why u use h2?)
mb just span?

2020-10-23 23:45 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
>  const MethodInfoLabel = coveredMethodsByTestSidebar.methodInfoLabel('div');
![image](https://user-images.githubusercontent.com/41574246/97062103-153aea80-15a2-11eb-9414-1d02a33b56f1.png)

2020-10-23 23:45 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss
>      min-width: 29px;
magic value

2020-10-24 10:20 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
>  const MethodInfoLabel = coveredMethodsByTestSidebar.methodInfoLabel('div');
where is the connection?

2020-10-26 08:04 UTC, RomanAchilov requested changes

2020-10-26 08:04 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.module.scss
> +    margin-left: 32px;
⬆️ 
check guide

2020-10-26 08:04 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.module.scss
> +    margin-left: 16px;
⬆️
check guide

2020-10-26 12:25 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss
> +    flex: none;
if I don't use `flex: none` then block has not fixed height

2020-10-27 08:57 UTC, RomanAchilov requested changes

2020-10-27 08:57 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss
>      padding-left: 24px;
check style guide

2020-10-27 08:57 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss
> +    height: 20px;
check style guide

2020-10-27 08:57 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.module.scss
>      height: 84px;
⬆️

2020-10-27 11:55 UTC, RomanAchilov approved these changes

2020-10-31 13:05 UTC, pavyarov requested changes

2020-10-31 13:05 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/methods-list/methods-list.tsx
> +      <SearchPanel>
search is unexpected in realization, remove it

2020-10-31 13:08 UTC, pavyarov approved these changes

2020-10-31 13:10 UTC, merged