EPMDJ-4842: Update progress bar animation
Drill4J/admin-ui pull request #416
Opened 2020-10-20 15:25 UTC by IliaSolovev

Issue: EPMDJ-4842

2020-10-22 14:29 UTC, RomanAchilov approved these changes

2020-10-23 12:42 UTC, pavyarov requested changes
update ui-kit version

2020-10-28 08:09 UTC, RomanAchilov requested changes

2020-10-28 08:09 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/active-build-coverage-info/multi-progress-bar/multi-progress-bar.module.scss
> +  &__additional-progress-bar-without-transition {
![image](https://user-images.githubusercontent.com/41574246/97409021-03dd3f80-190e-11eb-9236-d04310e8713d.png)

2020-10-28 12:59 UTC, pavyarov approved these changes

2020-10-28 12:59 UTC, merged