EPMDJ-4839: Add bulk aborting/finishing sessions
Drill4J/admin-ui pull request #417
Opened 2020-10-21 08:58 UTC by IliaSolovev

Issue: EPMDJ-4839

2020-10-23 12:52 UTC, pavyarov commented
Converted to Draft. Need to approve from BA team.

2020-10-28 11:19 UTC, RomanAchilov requested changes

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +                <span>
ActionsPanel

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +                  <BulkOperationButton
just Button

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +                    onClick={() => {
onClick={() => dispatch(setAbortingSessionsIsProcessing(true))}

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/service-group-sessions/service-group-sessions.module.scss
> +      opacity: 0.2;
Exactly 0.2? Usually 0.25

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +import { capitalize } from '../../../../utils';
from 'utils'

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +    const finishingSessionIsProcessing = finishingSessionIdByAgentId === sessionId + agentId;
abortingSessionIsProcessing and finishingSessionIsProcessing
it seems that this can be combined under a generic name

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +                    dispatch(setAbortingSessionIdByAgentId(sessionId + agentId));
onClick={() =>  dispatch(setAbortingSessionIdByAgentId(sessionId + agentId))}

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane-api/abort-all-sessions.ts
> +  pluginId: string,
{}

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane-api/finish-all-sessions.ts
> +  pluginId: string,
{}

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane.module.scss
> +  &__approve-action-wrapper {
?

2020-10-28 11:19 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +    }, dispatch] = React.useReducer(sessionPaneReducer, initialState);
😨

2020-10-28 19:37 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/manage-active-sessions/service-group-sessions/service-group-sessions.module.scss
> +      opacity: 0.2;
yes 
![image](https://user-images.githubusercontent.com/49729985/97487591-2141f600-196e-11eb-954e-202934178946.png)

2020-10-28 19:39 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +    const finishingSessionIsProcessing = finishingSessionIdByAgentId === sessionId + agentId;
i use both this variable later that i can show different warnings

2020-10-29 09:57 UTC, RomanAchilov requested changes

2020-10-29 09:57 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +  actionsState: {
strange name

2020-10-29 09:57 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +  actionSetters: {
strange name

2020-10-29 09:57 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +    setFinishingSessionsIsProcessing: (isProcessing: boolean) => void,
it seems that you can do one action

2020-10-29 09:57 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +    const disabledActions = isApprovingSessionsAction || Boolean(abortingSessionIdByAgentId) || Boolean(finishingSessionIdByAgentId);
disabled not only Actions

2020-10-29 09:57 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/operation-action-warning/operation-action-warning.tsx
> +      {operationType === 'abort' ? (
![image](https://user-images.githubusercontent.com/41574246/97553092-14f97f80-19e6-11eb-8a47-701e87c8462c.png)

2020-10-29 10:10 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +    const disabledActions = isApprovingSessionsAction || Boolean(abortingSessionIdByAgentId) || Boolean(finishingSessionIdByAgentId);
only finish and abort all actions

2020-10-30 08:23 UTC, RomanAchilov requested changes

2020-10-30 08:23 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-active-sessions/session-info/session-info.tsx
> +import { OperationActionWarning } from 'modules/manage-sessions-pane/operation-action-warning';
correct

2020-10-30 08:23 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/search-panel/search-panel.tsx
> +        <ActionsPanel>
This is a search bar. But it contains actions that are not related to the search.

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +                  onClick={() => {
```suggestion
                  onClick={() => setFinishingSessionIdByAgentId(sessionId + agentId);
```

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/manage-sessions-pane-api/finish-all-sessions.ts
> +  { agentId, agentType, pluginId } : { agentType: string, agentId: string, pluginId: string },
can you write interface?

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/manage-sessions-pane-reducer/manage-sessions-pane-reducer.spec.ts
> +        singleOperation: {id: "test", operationType: 'abort'}
```suggestion
        singleOperation: { id: "test", operationType: 'abort' }
```

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/manage-sessions-pane-reducer/manage-sessions-pane-reducer.spec.ts
> +        bulkOperation: {isProcessing: true, operationType: 'abort'}
```suggestion
        bulkOperation: { isProcessing: true, operationType: 'abort' }
```

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/manage-sessions-pane-reducer/manage-sessions-pane-reducer.spec.ts
> +    expect(sessionPaneReducer(initialState, {type: SET_IS_NEW_SESSION, payload: true}))
as above

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/manage-sessions-pane-reducer/manage-sessions-pane-reducer.spec.ts
> +    expect(sessionPaneReducer(initialState, {type: SET_BULK_OPERATION, payload: {isProcessing: true, operationType: 'abort'}}))
as above

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/operation-action-warning/operation-action-warning.tsx
> +  handleDecline : () => void;
```suggestion
  handleDecline: () => void;
```

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/operation-action-warning/operation-action-warning.tsx
> +  handleConfirm : () => void;
as above

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/operation-action-warning/operation-action-warning.tsx
> +      <span>
in one line

2020-11-05 17:45 UTC, SMPlay commented on src/modules/manage-sessions-pane/active-sessions-list/service-group-sessions/service-group-sessions.tsx
> +                disabled={Boolean(singleOperation.id) || bulkOperation.isProcessing}
can you use `!!` operator?

2020-11-06 07:13 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/active-sessions-list/service-group-sessions/service-group-sessions.tsx
> +                disabled={Boolean(singleOperation.id) || bulkOperation.isProcessing}
yes but i think that it look better

2020-11-11 07:49 UTC, pavyarov requested changes

2020-11-11 07:49 UTC, pavyarov commented on src/modules/manage-sessions-pane/actions-panel/actions-panel.module.scss
> +  padding: 0 24px;
Padding in block. Great!

2020-11-11 07:49 UTC, pavyarov commented on src/modules/manage-sessions-pane/actions-panel/actions-panel.module.scss
> +  margin-top: auto;
And margin in block

2020-11-11 07:49 UTC, pavyarov commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +    const { pluginId = '' } = useParams<{ pluginId: string;}>();
```suggestion
    const { pluginId = '' } = useParams<{ pluginId: string; }>();
```

2020-11-11 07:49 UTC, pavyarov commented on src/modules/manage-sessions-pane/bulk-operation-warning-panel/bulk-operation-warning-panel.module.scss
> +    padding: 12px 24px;
Padding in block

2020-11-11 07:49 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.module.scss
> +  padding: 16px 24px 10px 24px;
Again

2020-11-11 07:49 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-active-sessions/manage-active-sessions.tsx
> +import { useSessionsPaneDispatch, useSessionsPaneState } from '../store/sessions-pane-context';
Imports after styles

2020-11-11 07:49 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-sessions-pane-api/abort-all-sessions.ts
> +  { agentId, agentType, pluginId } : { agentId: string, agentType: string, pluginId: string },
```suggestion
  { agentId, agentType, pluginId }: { agentId: string, agentType: string, pluginId: string },
```

2020-11-11 10:09 UTC, RomanAchilov requested changes

2020-11-11 15:27 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/active-sessions-list/service-group-sessions/service-group-sessions.tsx
> +                disabled={Boolean(singleOperation.id) || bulkOperation.isProcessing}
it doesn't read consistently.

2020-11-11 15:30 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +        {singleOperation.operationType === 'abort' && operationIsProcessing && (
```suggestion
        {singleOperation.operationType === 'abort' && operationIsProcessing ? (
```

2020-11-11 15:31 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +        {singleOperation.operationType === 'finish' && operationIsProcessing && (
```suggestion
        : (
```

2020-11-11 16:03 UTC, RomanAchilov requested changes

2020-11-11 16:12 UTC, RomanAchilov requested changes

2020-11-11 16:12 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +  showGeneralAlertMessage: (message: Message) => void;
?

2020-11-11 16:12 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +        {!operationIsProcessing && (
?

2020-11-12 10:35 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +  showGeneralAlertMessage: (message: Message) => void;
it require because if i use it in children components react can`t show message. It show me error in console

2020-11-12 10:42 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/single-operation-warning/single-operation-warning.tsx
> +export const SingleOperationWarning = ({ agentId, sessionId, pluginId }: Props) => {
I have similar component but by bulk operation. I have not another idea for resolve problems with complex ternary operator. This components has different props, messages and handler on buttons.

2020-11-12 13:36 UTC, RomanAchilov requested changes

2020-11-12 13:36 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/active-sessions-list/session-info/session-info.tsx
> +    const { pluginId = '' } = useParams<{ pluginId: string, }>();
```suggestion
    const { pluginId = '' } = useParams<{ pluginId: string }>();
```
😠

2020-11-12 13:36 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane-api/finish-all-sessions.ts
> +      text: ' Sessions have been finished successfully. All your progress has been added to the active scope.',
```suggestion
      text: 'Sessions have been finished successfully. All your progress has been added to the active scope.',
```
😭

2020-11-12 17:32 UTC, merged