Integrate new ui-kit tables. Update styles. Create Cells componen
Drill4J/admin-ui pull request #422
Opened 2020-10-23 15:34 UTC by RomanAchilov

2020-10-23 16:03 UTC, IliaSolovev requested changes

2020-10-23 16:03 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/coverage-details/table/expandable-table/row-expander/row-expander.module.scss
> +    color: map-get($color-palette, blue100);
change color

2020-10-23 16:52 UTC, IliaSolovev requested changes

2020-10-23 16:52 UTC, IliaSolovev commented on src/components/cells/compound-cell/compound-cell.module.scss
> +    font-family: $semibold-font;
I think that you should paste here `width: 100%` because in another way we will se it.
![image](https://user-images.githubusercontent.com/49729985/97031638-4a771680-1569-11eb-80ba-aadc2dd0ff44.png)

2020-10-23 18:01 UTC, RomanAchilov commented on src/components/cells/compound-cell/compound-cell.module.scss
> +    font-family: $semibold-font;
Yes. I forgot to return it when I tried different solutions.
ty dude

2020-10-23 18:03 UTC, RomanAchilov commented on src/components/cells/compound-cell/compound-cell.module.scss
> +    font-family: $semibold-font;
There is such a problem without using " grid"
![image](https://user-images.githubusercontent.com/41574246/97038216-1ef92980-1573-11eb-9379-eb0fc035c58f.png)
I want to correct it differently

2020-10-25 21:01 UTC, IliaSolovev approved these changes

2020-10-26 11:21 UTC, pavyarov requested changes

2020-10-26 11:21 UTC, pavyarov commented on src/components/cells/count-cell/count-cell.tsx
> +export const CountCell = BEM(styles)(div({ onClick: () => {} } as { clickable?: boolean }));
ClickableCell

2020-10-26 11:21 UTC, pavyarov commented on src/components/cells/coverage-cell/coverage-cell.tsx
> +          title="Test didn't cover any methods. Make sure the test is actual or modify/delete it."
Not sure it's good idea. Are u sure this appears at all coverage cell?

2020-10-26 11:21 UTC, pavyarov commented on src/components/cells/duration-cell/duration-cell.module.scss
> +    color: map-get($monochrome, dark-tint);
Emm. This is strange too

2020-10-26 11:21 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-cell/coverage-cell.module.scss
> +.outdated-coverage-cell {
That is that?

2020-10-26 11:21 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/coverage-details/table/default-header-cell.tsx
> +    {name !== 'selector' && <SortArrows order={name === sort.fieldName ? sort.order : null} /> }
Name !== selector?

2020-10-26 13:26 UTC, pavyarov requested changes

2020-10-26 13:26 UTC, pavyarov commented on src/components/cells/clickable-cell/clickable-cell.module.scss
> +  &--clickable {
so u rename this component, i think u will refactor this to disabled?

2020-10-26 14:32 UTC, pavyarov approved these changes

2020-10-26 14:32 UTC, merged