EPMDJ-4411: Correct redirects at finish scope
Drill4J/admin-ui pull request #423
Opened 2020-10-26 12:15 UTC by SMPlay

Issue: EPMDJ-4411

2020-10-26 15:10 UTC, RomanAchilov approved these changes

2020-10-27 09:13 UTC, pavyarov requested changes

2020-10-27 09:13 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +    const isAllScopesPage = pathname.includes('scopes');
this is not true. scope info page includes `/scopes/`

2020-10-27 09:13 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +    const isActiveScopePage = scope?.id && pathname.includes(scope.id);
```suggestion
    const isScopeInfoPage = scope?.id && pathname.includes(scope.id);

```

2020-10-29 10:13 UTC, RomanAchilov requested changes

2020-10-29 10:13 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +                  ((!testsCount && isScopeInfoPage) || (testsCount === 1 && recordTests && !isAllScopesPage))
the condition is according to specification? It looks strange

2020-10-29 10:43 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +                  ((!testsCount && isScopeInfoPage) || (testsCount === 1 && recordTests && !isAllScopesPage))
if the coverage is not fixed in the scope and tests are written, then the scope will be deleted and a redirect will occur. If I can test it differently then the condition looks better

2020-10-29 11:04 UTC, RomanAchilov requested changes

2020-10-29 11:04 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +                  ((!testsCount && isScopeInfoPage) || (testsCount === 1 && recordTests && !isAllScopesPage))
specification

2020-10-31 12:55 UTC, pavyarov approved these changes

2020-10-31 12:56 UTC, merged