EPMDJ-4838: Implement tests-to-run page for singl agent
Drill4J/admin-ui pull request #425
Opened 2020-10-26 20:42 UTC by RomanAchilov

Issue: EPMDJ-4838

2020-10-28 11:52 UTC, IliaSolovev requested changes

2020-10-28 11:52 UTC, IliaSolovev commented on src/modules/covered-methods-by-test-sidebar/covered-methods-by-test-sidebar.tsx
> +    const filtredMethods = coveredMethodsByTest.find(({ id }) => id === testId) || {};
`filteredMethods`

2020-10-28 11:52 UTC, IliaSolovev commented on src/modules/tests-to-run-list/tests-to-run-header/get-suggested-tests-modal/get-suggested-tests-modal.module.scss
> +    &:hover {
add empty line

2020-11-06 08:14 UTC, SMPlay commented on src/modules/tests-to-run-list/tests-to-run-header/get-suggested-tests-modal/tests-to-run-url.module.scss
> +  min-width: 370px;
min-width == max-width?

2020-11-06 08:14 UTC, SMPlay commented on src/modules/tests-to-run-list/tests-to-run-header/get-suggested-tests-modal/tests-to-run-url.tsx
> +        <CurlFlag>curl <CurlFlag color="red">-</CurlFlag>i <CurlFlag color="red">-</CurlFlag>H </CurlFlag>
&ndash

2020-11-06 08:14 UTC, SMPlay commented on src/modules/tests-to-run-modal/tests-to-run-modal.module.scss
>      font-size: 14px;
down

2020-11-06 08:40 UTC, RomanAchilov commented on src/modules/tests-to-run-modal/tests-to-run-modal.tsx
> +  byType?: { [key: string]: string[] };
reason?

2020-11-06 08:47 UTC, IliaSolovev requested changes

2020-11-06 08:47 UTC, IliaSolovev commented on src/modules/tests-to-run-list/tests-to-run-list.tsx
> +          Displaying {testsToRun.length} of {testsToRun.length} tests
are you sure that it is correct logic? If your search return nothing you will show `Displaying 0 of 0 tests`

2020-11-06 08:47 UTC, IliaSolovev commented on src/modules/tests-to-run-modal/tests-to-run-modal.tsx
> +import { useParams } from 'react-router-dom';
up

2020-11-06 08:47 UTC, IliaSolovev commented on src/types/search.ts
> +  fieldName: string;
can you rename it like field? later BE will take data with so name in filters and sorting. it can help later for us

2020-11-06 08:47 UTC, IliaSolovev commented on src/types/sort.ts
> +  fieldName: string;
can you rename it like field? later BE will take data with so name in filters and sorting. it can help later for us

2020-11-06 08:55 UTC, RomanAchilov commented on src/modules/tests-to-run-list/tests-to-run-list.tsx
> +          Displaying {testsToRun.length} of {testsToRun.length} tests
need discuss with BA design and BE

2020-11-06 08:57 UTC, RomanAchilov commented on src/modules/tests-to-run-list/tests-to-run-list.tsx
> +          Displaying {testsToRun.length} of {testsToRun.length} tests
the initial t2r count is currently missing

2020-11-06 09:19 UTC, SMPlay commented on src/modules/tests-to-run-modal/tests-to-run-modal.tsx
> +  byType?: { [key: string]: string[] };
Pavel sad me do so, when I wrote key-construction

2020-11-06 17:11 UTC, RomanAchilov commented on src/modules/tests-to-run-modal/tests-to-run-modal.tsx
> +  byType?: { [key: string]: string[] };
ok ;D

2020-11-08 17:03 UTC, SMPlay commented on .env.local
> +REACT_APP_API_HOST=ecse00500994.epam.com:8090
😡

2020-11-09 20:04 UTC, merged