EPMDJ-4840: Update build/scope test table
Drill4J/admin-ui pull request #426
Opened 2020-10-27 10:32 UTC by IliaSolovev

Issue: EPMDJ-4840

2020-10-27 11:03 UTC, RomanAchilov requested changes

2020-10-27 11:03 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +const TestTypeCell = testDetails.testTypeCell('span');
we also want to unify the Cells used

2020-10-27 11:03 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
>  const StatusCell = testDetails.statusCell('span');
we also want to unify the Cells used

2020-10-27 11:03 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +                  <Cells.Compound cellName={testName} cellAdditionalInfo={id || '-'} icon={<Icons.Test height={16} width={16} />} />
`-` replace `&ndash;`

2020-10-28 07:58 UTC, RomanAchilov requested changes

2020-10-28 07:58 UTC, RomanAchilov commented on src/components/cells/status-cell/status-cell.module.scss
> +  font-size: 12px;
default

2020-10-28 07:58 UTC, RomanAchilov commented on src/components/cells/status-cell/status-cell.module.scss
> +  line-height: 16px;
default

2020-10-28 07:58 UTC, RomanAchilov commented on src/components/cells/status-cell/status-cell.tsx
> +import { capitalize } from '../../../utils';
from 'utils'

2020-10-28 07:58 UTC, RomanAchilov commented on src/components/cells/status-cell/status-cell.tsx
> +export const StatusCell = statusCell(({ className, value }: Props) => (
export const StatusCell = BEM(styles)("div")

2020-10-28 09:47 UTC, RomanAchilov approved these changes

2020-10-28 09:47 UTC, RomanAchilov commented on src/components/cells/status-cell/status-cell.module.scss
> +  &--type {
empty line

2020-10-29 09:23 UTC, pavyarov approved these changes

2020-10-29 09:24 UTC, merged