EPMDJ-4990: Remove test to run links from build tests card
Drill4J/admin-ui pull request #430
Opened 2020-11-02 13:00 UTC by IliaSolovev

Issue: EPMDJ-4990

2020-11-02 13:58 UTC, RomanAchilov requested changes

2020-11-02 13:58 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
>      const [testsFilter, setTestsFilter] = React.useState<string>('');
?

2020-11-02 14:03 UTC, RomanAchilov approved these changes

2020-11-03 13:25 UTC, pavyarov approved these changes

2020-11-03 13:28 UTC, merged