EPMDJ-4944: Update associated tests modal
Drill4J/admin-ui pull request #431
Opened 2020-11-02 14:28 UTC by SMPlay

Issue: EPMDJ-4912 EPMDJ-4944

2020-11-02 14:32 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.module.scss
> +    margin-left: 8px;
up

2020-11-02 14:32 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    flex-grow: 1;
?

2020-11-02 14:57 UTC, IliaSolovev requested changes

2020-11-02 14:57 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.module.scss
>      display: flex;
up

2020-11-02 14:57 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/item-info/item-info.module.scss
>      line-height: 32px;
down

2020-11-02 14:57 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    flex-grow: 1;
what does not so?

2020-11-02 14:57 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.tsx
> +              <TestItem key={tests[index]} style={style as any}>
you can type style like `Record<symbol, string>`

2020-11-02 14:57 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.tsx
> +                <TestId title="-">-</TestId>
`&ndash;`

2020-11-03 07:03 UTC, RomanAchilov requested changes

2020-11-03 07:03 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.tsx
> +                <TestId title="-">&ndash;</TestId>
?

2020-11-03 07:16 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/associated-test-modal.tsx
> +    const testsMap: Record<string, string[]> = tests.reduce((acc, { type = '', name = '' }) =>
no

2020-11-03 07:17 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    margin-left: 18px;
![image](https://user-images.githubusercontent.com/49731235/97958170-bce3c400-1dbd-11eb-98fb-d7a91fd6a20b.png)
mockup

2020-11-03 07:19 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    width: 298px;
![image](https://user-images.githubusercontent.com/49731235/97958316-03d1b980-1dbe-11eb-844a-0aa8303bb342.png)
mockup

2020-11-03 07:19 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    width: 298px;
![image](https://user-images.githubusercontent.com/49731235/97958342-121fd580-1dbe-11eb-9607-7255a4256e83.png)
mockup

2020-11-03 07:21 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.tsx
> +                <TestId title="-">&ndash;</TestId>
this is stub, because I haven't `testId` from BE (I have ONLY data: string[])

2020-11-03 07:26 UTC, IliaSolovev approved these changes

2020-11-03 07:27 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    width: 298px;
mb, can I use `calc(100% - 24px)`?

2020-11-03 10:01 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    width: 298px;
you don't need to set the width manually

2020-11-03 10:02 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    width: 298px;
you don't need to set The width manually

2020-11-03 10:02 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/coverage-details/tests-list/tests-list.module.scss
> +    margin-left: 18px;
must be 16

2020-11-08 10:13 UTC, RomanAchilov approved these changes

2020-11-10 08:32 UTC, pavyarov commented
@SMPlay just a remind. Sonar report is not a joke. Fix code smell plz.

2020-11-10 15:43 UTC, merged