EPMDJ-4917: Add onSubmit validation
Drill4J/admin-ui pull request #432
Opened 2020-11-02 18:04 UTC by RomanAchilov

Issue: EPMDJ-4917

2020-11-03 07:34 UTC, RomanAchilov commented on src/forms/form-validators.ts
> +  request: Promise<any>;
any?

2020-11-03 07:34 UTC, RomanAchilov commented on src/forms/form-validators.ts
> +export async function submissionValidate({ request, onSuccess, onError }: SubmissionValidate): Promise<any> {
any?

2020-11-03 07:34 UTC, RomanAchilov commented on src/forms/form-validators.ts
> +    const response = await request;
request?

2020-11-03 08:32 UTC, RomanDavlyatshin commented on src/forms/form-validators.ts
> +  } catch ({ response }) {
It looks unreliable:
1. `response` property is not guaranteed to be there;
2. an object in the catch clause could be anything - even `undefined`. It depends on what happens inside `request` on line 71.

I would rather do

```
...
catch (error) {
  const isConflictError = error?.response?.data?.code === 409 &&  error.response.data.data;
  if (isConflictError) {
    const { fieldErrors } = error.response.data.data; // that is still risky ("fieldErrors" might be missing), but we can trust backend, right ? :)
    // ... do stuff
  }
  // ... other stuff
}
```

2020-11-03 08:32 UTC, RomanDavlyatshin commented on src/forms/form-validators.ts
> +    const response = await request;
just `asyncFn` might be better
It could be anything, even call to some background process / local storage / etc.

2020-11-03 08:32 UTC, RomanDavlyatshin commented on src/forms/form-validators.ts
> +export async function submissionValidate({ request, onSuccess, onError }: SubmissionValidate): Promise<any> {
`unknown`  would be typesafe, but if you gonna cast it to `any` every single time, you might just leave it as-is

2020-11-03 08:32 UTC, RomanDavlyatshin commented on src/forms/form-validators.ts
> +  request: Promise<any>;
see comment on `unknown` bellow :)

2020-11-03 08:32 UTC, RomanDavlyatshin commented on src/forms/form-validators.ts
> +export async function submissionValidate({ request, onSuccess, onError }: SubmissionValidate): Promise<any> {
BTW, I hate that name. `submissionValidate` does nothing to suggest what it does :)

2020-11-03 08:32 UTC, RomanDavlyatshin commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +                  ? axios.post(`/agents/${agentId}/plugins/${pluginId}/dispatch-action`, {
Inlining axios calls making a template hard to read. I suggest to revert it back to separate function calls, that was better.

2020-11-03 08:32 UTC, RomanDavlyatshin commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +                        if (response?.status === 200) {
If handleSumbit throws, a form would not clean up
Also checking for `response?.status === 200` is bad because it forces you to pass HTTP response to a view.
I would rather do
```
onClick={async () => {
  try {
    await handleSubmit();
    // can move these two lines bellow to a separate `cleanup()` function for extra clarity
    form.change('sessionId', ''); 
    setIsNewSession(false);
  } catch (error) {
    // ??? something happens to the form, I guess. Or nothing (because errors already passed to onSumbit
  }
```

2020-11-03 08:36 UTC, RomanDavlyatshin commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +                        if (response?.status === 200) {
BTW there is `form.reset()` method available in react-final-form
No need to reset each field manually

2020-11-06 09:53 UTC, pavyarov requested changes

2020-11-06 09:53 UTC, pavyarov commented on src/forms/form-validators.ts
> +interface FieldErrors {
```suggestion
interface FieldError {

```

2020-11-06 09:53 UTC, pavyarov commented on src/forms/form-validators.ts
> +export async function asyncSubmit({ asyncFn, onSuccess, onError }: AsyncSubmit): Promise<unknown> {
generic type

2020-11-06 09:53 UTC, pavyarov commented on src/forms/form-validators.ts
> +        ({ ...acc, [current.field]: current.message }), {} as {[key: string]: string});
Record<string, string>

2020-11-09 13:26 UTC, pavyarov requested changes

2020-11-09 13:26 UTC, pavyarov commented on src/forms/form-validators.ts
> +  return (fieldErrors || []).reduce((acc, current) =>
🤣

2020-11-09 13:26 UTC, pavyarov commented on src/forms/form-validators.ts
> +export function handleFieldErrors(fieldErrors: FieldError[]): Record<string, string> {
```suggestion
export function handleFieldErrors(fieldErrors: FieldError[] = []): Record<string, string> {

```

2020-11-09 13:26 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +              return undefined;
ugh?

2020-11-09 19:21 UTC, merged