EPMDJ-5058: integration with new sort/filter realization
Drill4J/admin-ui pull request #435
Opened 2020-11-09 08:02 UTC by IliaSolovev

Issue: EPMDJ-5058, EPMDJ-5032

2020-11-09 14:08 UTC, pavyarov requested changes

2020-11-09 14:08 UTC, pavyarov commented on src/modules/table-actions/table-actions-context.ts
> +  search: [{ field: 'name', value: '', op: 'CONTAINS' }],
op has a default value at BE?

2020-11-09 14:08 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/coverage-details/coverage-details.tsx
> +            <SearchResult align={search[0].value ? 'space-between' : 'end'}>
`search[0]`?
if u need it, use turple

2020-11-09 14:08 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +  Icons, Column, Table, Panel,
?

2020-11-09 14:08 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/test-details/test-details.tsx
> +} from 'modules/table-actions';
?
```suggestion
} from 'modules';

```

2020-11-09 14:08 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/tests/tests.tsx
> +import { TableActionsProvider } from 'modules/table-actions';
?

2020-11-09 16:31 UTC, IliaSolovev commented on src/modules/table-actions/table-actions-context.ts
> +  search: [{ field: 'name', value: '', op: 'CONTAINS' }],
yes, default value is "EQ"

2020-11-10 15:00 UTC, RomanAchilov commented on src/modules/table-actions/reducer.ts
> +        sort: state.sort.map(({ fieldName, order }) => ({
const [sort] = state

2020-11-10 15:05 UTC, RomanAchilov commented on src/types/search.ts
> +  op?: 'CONTAINS' | 'EQ';
type Op = 'CONTAINS' | 'EQ';

2020-11-10 15:28 UTC, RomanAchilov requested changes

2020-11-10 15:28 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx
> +          onSearch={(value) => setSearch([{ fieldName: 'name', value, op: 'CONTAINS' }])}
?

2020-11-10 15:28 UTC, RomanAchilov commented on src/hooks/use-build-version.ts
> +        filters: filters?.map(({ fieldName, value, op }) => ({ field: fieldName, value, op })),
?

2020-11-10 15:28 UTC, RomanAchilov commented on src/hooks/use-build-version.ts
> +        orderBy: orderBy?.map(({ fieldName, order }) => ({ field: fieldName, order })),
?

2020-11-10 15:28 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx
> +          searchQuery={query.value}
searchQuery

2020-11-11 07:41 UTC, pavyarov requested changes

2020-11-11 07:41 UTC, pavyarov commented on src/types/search.ts
> +type OP = 'CONTAINS' | 'EQ';
Operator

2020-11-11 07:58 UTC, RomanAchilov requested changes

2020-11-11 07:58 UTC, RomanAchilov commented on src/hooks/use-build-version.ts
> +export function useBuildVersion<Data>(topic: string, filters?: Search[], orderBy?: Sort[]): Data | null {
filters?: Search[] 
?

2020-11-11 07:58 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx
> +import { Search } from 'types/search';
⬆️

2020-11-11 10:32 UTC, merged