EPMDJ-4918: Implement the ability to configure the session start as global and real-time
Drill4J/admin-ui pull request #440
Opened 2020-11-10 17:37 UTC by SMPlay

Issue: EPMDJ-4918

2020-11-11 07:38 UTC, pavyarov requested changes

2020-11-11 07:38 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
> +  &__custom-tooltip {
This is not ok. Plz contact design team. We have design system with tooltip. @RomanAchilov

2020-11-11 07:38 UTC, pavyarov commented on src/types/start-session.ts
> +export interface StartSession {
What is this?

2020-11-11 08:15 UTC, pavyarov commented on src/types/start-session.ts
> +export interface StartSession {
StartSessionPayload at least

2020-11-11 17:16 UTC, pavyarov requested changes

2020-11-11 17:16 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +              <Checkbox
`Fields.Checkbox`

2020-11-11 17:16 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +            <Checkbox
`Fields.Checkbox`

2020-11-11 17:16 UTC, pavyarov commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +                      text: fieldErrorsToObject?.sessionId,
@RomanAchilov Some strange logic is here. Plz check it before merge.

2020-11-11 21:38 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +                      text: fieldErrorsToObject?.sessionId,
yes

2020-11-12 07:29 UTC, SMPlay commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +              <Checkbox
If I'll use simple Fields.Checkbox then I can't use styles for checkboxes

2020-11-12 07:43 UTC, IliaSolovev requested changes

2020-11-12 07:43 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
> +      margin-top: 16px;
can you use flex-box in parent block instead it?

2020-11-12 07:43 UTC, IliaSolovev commented on src/modules/manage-sessions-pane/manage-sessions-pane-api/start-agent-session.ts
> +  return async ({ sessionId, isGlobal = false, isRealtime = false }: StartSessionPayload): Promise<void> => {
default values to these params is necessary?  Maybe BE have default value?

2020-11-12 08:25 UTC, RomanAchilov requested changes

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
> +    display: flex;
panel

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
>    &__new-session-form {
`
display: grid
gap: 16px
`

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
>    &__new-session-form {
or display: flex
flex-dir: col
gap: 16

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
>    &__new-session-form {
it is not necessary to use a margin inside the content blocks for indents

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
> +    margin-top: 16px;
it is not necessary to use a margin inside the content blocks for indents

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +                    </div>
1 line

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +              <Checkbox
u can

2020-11-12 08:25 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane.tsx
> +                  if (fieldErrors.length === 0) {
?

2020-11-12 11:21 UTC, RomanAchilov requested changes

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +      <Checkboxes direction="column" align="space-between" verticalAlign="start">
useless

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
> +  &__checkboxes {
useless

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
> +  &__checkboxes {
please think about how to write styles optimally

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +      <Checkboxes direction="column" align="space-between" verticalAlign="start">
please think about how to write styles optimally

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +const Checkboxes = manageNewSession.checkboxes(Panel);
delete. U use grid layout

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-sessions-pane-api/start-agent-session.ts
> +import { StartSessionPayload } from './start-session-payload';
```suggestion
import { StartSessionPayload } from './start-session-payload-types';
```

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.module.scss
> +    width: 184px;
gap: 8px

2020-11-12 11:21 UTC, RomanAchilov commented on src/modules/manage-sessions-pane/manage-new-session/manage-new-session.tsx
> +            <GlobalSessionCheckbox align="space-between">
```suggestion
            <GlobalSessionCheckbox>
```

2020-11-12 20:05 UTC, merged