EPMDJ-5234: Update active scope block
Drill4J/admin-ui pull request #456
Opened 2020-11-18 11:34 UTC by SMPlay

Issue: EPMDJ-5234

2020-11-18 12:55 UTC, RomanAchilov requested changes

2020-11-18 12:55 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx
> +        >Details
?

2020-11-18 12:55 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.tsx
> +        >All scopes
?

2020-11-18 12:55 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/overview.module.scss
> +  &__overview-layout {
it looks intricate

2020-11-18 12:55 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/overview.tsx
> +import { ProjectTestsCards } from '../project-tests-cards';
😠

2020-11-18 12:55 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/overview.tsx
> +          {selectedTab === 'methods' && <ProjectMethodsCards methods={buildMethods} />}
?

2020-11-18 16:05 UTC, IliaSolovev requested changes

2020-11-18 16:05 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/tests/tests.tsx
> -  const allTests = useBuildVersion<TestSummary>('/build/summary/tests/all') || {};
why you delete it all ?

2020-11-18 18:44 UTC, RomanDavlyatshin requested changes

2020-11-18 18:44 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.module.scss
> +  width: 312px;
Don't use a fixed width inside the component.
Set component width with the layout instead.

2020-11-18 18:44 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.module.scss
> +    width: 248px;
Do not use fixed with.
Try to solve that with parent layout/margin/padding etc

2020-11-18 18:44 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/overview/overview.module.scss
> +    &--active-scope {
😠 redundant modifier `--active-scope` + redundant calc + magic numbers
Solve that with **the parent layout**

2020-11-18 18:44 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/overview/overview.module.scss
> +    height: 272px;
Why use fixed height? Summary Panel has content inside

2020-11-19 13:13 UTC, IliaSolovev approved these changes

2020-11-20 09:18 UTC, RomanAchilov requested changes

2020-11-20 09:18 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.module.scss
> +  &__actions {
panel

2020-11-20 09:18 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/overview/overview.tsx
> +        <SummaryPanel
?

2020-11-20 09:37 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/overview/active-scope-info/active-scope-info.module.scss
> +  &__actions {
I can't use `Panel`, because it has `width: 100%` and it turns out like this:
![image](https://user-images.githubusercontent.com/49731235/99784517-faba4980-2b2c-11eb-832f-73c256fc2595.png)
Also I can't use `width: max-content`, because in build it doesn't work

2020-11-24 14:51 UTC, RomanAchilov approved these changes

2020-11-25 14:27 UTC, RomanAchilov approved these changes

2020-11-25 14:28 UTC, merged