EPMDJ-5235: update cards for build methods and tests
Drill4J/admin-ui pull request #457
Opened 2020-11-18 12:40 UTC by IliaSolovev

Issue: EPMDJ-5235

2020-11-18 13:20 UTC, RomanAchilov requested changes

2020-11-18 13:20 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.module.scss
> +  grid-template-columns: 1fr 1fr 1fr;
repeat

2020-11-18 13:49 UTC, RomanAchilov requested changes

2020-11-18 13:49 UTC, RomanAchilov commented on src/components/cards-additional-info/build-methods/build-methods.tsx
> +  covered?: number | string;
?

2020-11-18 13:49 UTC, RomanAchilov commented on src/components/cards-additional-info/index.ts
> +export const CardsAdditionalInfo = {
(

2020-11-18 13:49 UTC, RomanAchilov commented on src/components/info-card/info-card.tsx
> +  AdditionalInfo: () => JSX.Element | null;
?

2020-11-18 15:20 UTC, RomanAchilov requested changes

2020-11-18 15:20 UTC, RomanAchilov commented on src/components/cards/build-methods/build-methods.tsx
> +
😠

2020-11-18 15:20 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +
?

2020-11-18 15:20 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +
?

2020-11-18 18:03 UTC, RomanAchilov requested changes

2020-11-18 18:03 UTC, RomanAchilov commented on src/components/cards/index.ts
> +export const Cards = {
need > 3

2020-11-18 18:11 UTC, RomanDavlyatshin requested changes

2020-11-18 18:11 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +    const testsInfo: TestsInfo = testsByType?.reduce((test, testType) => ({ ...test, [testType.type]: testType }), {}) || {};
Redundant `|| {}`

2020-11-18 18:11 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/scope/scope-info/scope-info.tsx
> +                  <ProjectTestsCards testsByType={scopeTestsByType} testTypeOverlap={testTypeOverlap} />
Reduce `scopeTestsByType` and `testTypeOverlap` to homogenous object and pass a **single** prop to `ProjectTestsCards`

2020-11-18 18:11 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/tests/tests.tsx
> +  const { byTestType, testTypeOverlap } = useBuildVersion<BuildCoverage>('/build/coverage') || {};
Same as `scope-info.tsx` - reduce to a single object, pass single prop.

2020-11-19 08:26 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +    const testsInfo: TestsInfo = testsByType?.reduce((test, testType) => ({ ...test, [testType.type]: testType }), {}) || {};
it necessary because testsByType can be undefined

2020-11-19 08:28 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/tests/tests.tsx
> +  const { byTestType, testTypeOverlap } = useBuildVersion<BuildCoverage>('/build/coverage') || {};
i will reduce to single object in JSX

2020-11-20 09:07 UTC, pavyarov requested changes

2020-11-20 09:07 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +          <span>
DeletedCount is already span

2020-11-20 09:07 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +              data-test="info-card:link-button:modified:risks"
This is from spec? Looks ugly.

2020-11-20 09:07 UTC, pavyarov commented on src/components/cards/build-tests/build-tests.tsx
> +  percentage?: number;
Here u pass percentage, at buildmerhods u pass total and covered and calc percentage. It's not ok

2020-11-20 09:07 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +    const testsInfo: TestsInfo = tests.byType?.reduce((test, testType) => ({ ...test, [testType.type]: testType }), {}) || {};
`|| {}` for what?

2020-11-20 09:28 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +    const testsInfo: TestsInfo = tests.byType?.reduce((test, testType) => ({ ...test, [testType.type]: testType }), {}) || {};
tests.byType can be undefined

2020-11-20 16:26 UTC, IliaSolovev commented on src/components/cards/build-tests/build-tests.tsx
> +  percentage?: number;
If in buildMethods I have all data so that I can calc the percentage inside the component. Should I take the percentage from props?

2020-11-20 16:33 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +    const testsInfo: TestsInfo = tests.byType?.reduce((test, testType) => ({ ...test, [testType.type]: testType }), {}) || {};
Are you want that I use default value in component args? I think that in so way code will be ugly. Because when I read `tests.byType` look better than `byType`. I can rename props but I think that it has a good name.
![image](https://user-images.githubusercontent.com/49729985/99824811-438ef400-2b67-11eb-9146-a3ffe8ed0bcd.png)

2020-11-20 16:36 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +          <span>
I use so wrapper because in buildMethods component I write it
![image](https://user-images.githubusercontent.com/49729985/99825063-9ec0e680-2b67-11eb-9bd5-c3deefba0f49.png)

2020-11-24 11:08 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +              data-test="info-card:link-button:modified:risks"
yes

2020-11-24 13:06 UTC, SMPlay commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +    const testsInfo: TestsInfo = byType?.reduce((test, testType) => ({ ...test, [testType.type]: testType }), {});
?

2020-11-24 13:11 UTC, SMPlay approved these changes

2020-11-24 14:42 UTC, RomanAchilov requested changes

2020-11-24 14:42 UTC, RomanAchilov commented on src/components/cards/build-methods/build-methods.module.scss
> +.build-methods {
```suggestion
.build-methods-card {
```

2020-11-24 14:42 UTC, RomanAchilov commented on src/components/cards/build-tests/build-tests.module.scss
> +.build-tests {
build-tests-card

2020-11-24 14:42 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +          percentage={(Number(testsInfo?.AUTO?.summary?.testCount) / totalTests) * 100}
not very reliable calculations. But the percentFormatter will save you.

2020-11-25 07:12 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +          percentage={(Number(testsInfo?.AUTO?.summary?.testCount) / totalTests) * 100}
There is `convertToPercentage` function added in `build-methods.tsx `.
Move it to the `utils` folder and use it here as well.

2020-11-25 07:13 UTC, RomanDavlyatshin approved these changes

2020-11-25 11:07 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +          <span>
Move wrapper to compinent

2020-11-25 11:08 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/project-methods-cards/project-methods-cards.tsx
> +              data-test="info-card:link-button:modified:risks"
So BEM notation is ruined. @RomanAchilov I think u should keep BEM at data-test attrs too

2020-11-25 11:09 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/project-tests-cards/project-tests-cards.tsx
> +          percentage={(Number(testsInfo?.AUTO?.summary?.testCount) / totalTests) * 100}
@IliaSolovev don't forget about unit tests

2020-11-26 08:41 UTC, pavyarov requested changes

2020-11-26 08:41 UTC, pavyarov commented on src/utils/convert-to-percentage.ts
> +  return denominator !== 0 && !Number.isNaN(numerator) && !Number.isNaN(denominator) && Number.isFinite(denominator)
Kinda unreadable, maybe default if statements will be better.

2020-11-26 12:24 UTC, RomanDavlyatshin requested changes

2020-11-26 12:24 UTC, RomanDavlyatshin commented on src/utils/convert-to-percentage.ts
> +  return denominator !== 0 && !Number.isNaN(numerator) && !Number.isNaN(denominator) && Number.isFinite(denominator)
1. 👍 to pavyarov. Do not overuse ternary operators, they aren't a replacement for `if`
2. Lot's of not operators (`!`) make it hard to read as well. Just do a straightforward check and use logical or (`||`)
```
function convertToPercentage(numerator, denominator) {
  if (denominator == 0 ||
    Number.isNaN(numerator) ||
    Number.isNaN(denominator) ||
    !Number.isFinite(denominator)) { // Isn't that much easier to read than a long ternary operator ? 😄 
    return 0;
  }
  return (numerator / denominator) * 100;
}
```
3. Pass `Infinity` to the `numerator` and see what happens 😄

2020-12-21 20:13 UTC, RomanAchilov approved these changes

2020-12-21 20:28 UTC, merged