EPMDJ-5304: added no plugins stub to service group dashboard page
Drill4J/admin-ui pull request #463
Opened 2020-11-23 10:11 UTC by IliaSolovev

Issue: EPMDJ-5304

2020-11-23 11:28 UTC, pavyarov requested changes
``

2020-11-23 11:28 UTC, pavyarov commented on src/modules/no-plugins-stub/no-plugins-stub.tsx
> +  agentType: 'Agent' | 'Service group';
Service group everywhere is `ServiceGroup`

2020-11-23 11:28 UTC, pavyarov commented on src/pages/service-group-full-page/dashboard/dashboard.module.scss
> +.dashboard-service-group-page {
`service-group-dashboard-page`

2020-11-23 15:47 UTC, SMPlay approved these changes

2020-11-24 07:34 UTC, RomanAchilov requested changes

2020-11-24 07:34 UTC, RomanAchilov commented on src/modules/no-plugins-stub/no-plugins-stub.tsx
> +    <AgentInfoLink to={`/agents/${spacesToDashes(camelToSpaces(agentType))}/${agentId}/settings`}>
```suggestion
    <AgentInfoLink to={`/agents/${agentType === 'Agent' ? agent : service-group} /${agentId}/settings`}>
```

2020-11-24 07:45 UTC, RomanAchilov approved these changes

2020-11-24 07:46 UTC, merged