EPMDJ-5260: Add the ability to toggle baseline
Drill4J/admin-ui pull request #464
Opened 2020-11-23 10:16 UTC by RomanAchilov

Issue: EPMDJ-5260

2020-11-23 11:25 UTC, pavyarov requested changes

2020-11-23 11:25 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/api/toggle-baseline.ts
> +    onError && onError(message);
No default message?

2020-11-23 11:25 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
> +  const { version: baseline } = useBuildVersion<Record<string, string>>('/data/baseline') || {};
Record?

2020-11-23 11:25 UTC, pavyarov commented on src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
> +    baseline && setIsBaseline(baseline === buildVersion);
Funny

2020-11-23 11:57 UTC, RomanDavlyatshin requested changes

2020-11-23 12:25 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/api/toggle-baseline.ts
> +  } catch ({ response: { data: { message } = {} } = {} }) {
`data` might be undefined, that's gonna break

2020-11-23 12:25 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
> +    baseline && setIsBaseline(baseline === buildVersion);
Can you elaborate, please? 😃

2020-11-23 15:58 UTC, RomanDavlyatshin requested changes

2020-11-23 15:58 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
> +          {((!previousBuildVersion && isBaseline) ||
Refactor repeated conditions checks (1. before &&, 2. `disabled` prop, 3. inside Panel) to a single function call

2020-11-23 15:58 UTC, RomanDavlyatshin commented on src/pages/agent-full-page/coverage-plugin/coverage-plugin-header/coverage-plugin-header.tsx
> +      {isRisksModalOpen && <RisksModal isOpen={isRisksModalOpen} onToggle={setIsRisksModalOpen} />}
I don't understand: what's the point in passing `isRisksModalOpen` to a prop `isOpen` along with `{isRisksModalOpen && (` check?
I mean, if `isRisksModalOpen === false` then `<RisksModal>` won't even render, right?
Either do the check (and remove `isOpen`) or remove the check and let `<RisksModal>` to manage its rendering with `isOpen`.

2020-11-24 14:01 UTC, RomanDavlyatshin approved these changes

2020-11-24 14:02 UTC, merged