EPMDJ-5284: Remove "Get Suggested Tests" button from non-latest builds
Drill4J/admin-ui pull request #465
Opened 2020-11-23 13:55 UTC by SMPlay

Issue: EPMDJ-5284

2020-11-23 14:06 UTC, IliaSolovev approved these changes

2020-11-24 07:19 UTC, RomanAchilov requested changes

2020-11-24 07:19 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +  const isLastBuild = activeBuildVersion === buildVersion;
delete

2020-11-24 07:19 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +          {isLastBuild && (
`activeBuildVersion === buildVersion`

2020-11-24 07:19 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +  const { agentId } = usePluginState();
take from useParams

2020-11-24 07:54 UTC, RomanAchilov approved these changes

2020-11-24 07:54 UTC, merged