EPMDJ-5316: support topic "/build/summary" for dashboard page
Drill4J/admin-ui pull request #468
Opened 2020-11-25 07:02 UTC by SMPlay

Issue: EPMDJ-5316

2020-11-25 07:44 UTC, IliaSolovev requested changes

2020-11-25 07:44 UTC, IliaSolovev commented on src/types/build-summary.ts
> +export interface BuildSummary {
are you sure that all these properties BE will give? Mb you`ll use optional chaining here

2020-11-25 07:47 UTC, SMPlay commented on src/types/build-summary.ts
> +export interface BuildSummary {
yes

2020-11-25 12:48 UTC, RomanAchilov requested changes

2020-11-25 12:48 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/sections/risks-section.tsx
> +              percent={(newMethodsCount / total) * 100}
can be NaN

2020-11-25 12:48 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/sections/risks-section.tsx
> +              percent={(modifiedMethodsCount / total) * 100}
can be NaN

2020-11-25 12:48 UTC, RomanAchilov commented on src/pages/agent-full-page/dashboard/sections/tests-to-run-section.tsx
> +                percent={(testsToRunByType[testType as TestTypes] / count) * 100}
can be NaN

2020-11-25 12:48 UTC, RomanAchilov commented on src/types/build-summary.ts
> +}
```suggestion
}
export interface BuildSummary {
  coverage?: number;
  coverageCount?: Count;
  scopeCount?: number;
  arrow?: ArrowType;
  riskCounts?: RisksSummary;
  tests?: TestCount;
  testsToRun?: TestCount;
  recommendations?: string[];
}
```

2020-11-26 08:39 UTC, pavyarov commented on src/pages/agent-full-page/dashboard/sections/risks-section.tsx
> +              percent={(newMethodsCount / total) * 100}
Use convert util from #457

2020-11-27 16:31 UTC, RomanAchilov approved these changes

2020-11-27 16:31 UTC, merged