EPMDJ-5376: Update finish and delete scope flow
Drill4J/admin-ui pull request #472
Opened 2020-11-26 15:51 UTC by SMPlay

Issue: EPMDJ-5376

2020-11-26 17:06 UTC, IliaSolovev requested changes

2020-11-26 17:13 UTC, SMPlay commented on src/components/active-sessions-warning/active-sessions-warning.tsx
> +      At least one active session has been detected.<br />
I think that one `<br />` looks better than two `div`

2020-11-26 17:40 UTC, RomanAchilov requested changes

2020-11-26 17:40 UTC, RomanAchilov commented on src/components/active-sessions-warning/active-sessions-warning.tsx
> +const SessionsManagementButton = activeSessionsWarning.sessionsManagementButton('span');
It's a LinkButton 
![image](https://user-images.githubusercontent.com/41574246/100378715-afb89e80-3024-11eb-919d-0f3278fa7af8.png)

2020-11-26 17:40 UTC, RomanAchilov commented on src/components/active-sessions-warning/active-sessions-warning.tsx
> +export const ActiveSessionsWarning = activeSessionsWarning(({ className, onClick }: Props) => (
Don’t repeat yourself – but don’t overdo it

2020-11-27 10:46 UTC, SMPlay commented on src/pages/service-group-full-page/test-to-code-plugin/test-to-code-plugin.tsx
> +      <div className={className}>
no, I just removed react fragment)

2020-11-27 10:53 UTC, SMPlay commented on src/components/active-sessions-warning/active-sessions-warning.tsx
> +const SessionsManagementButton = activeSessionsWarning.sessionsManagementButton('span');
I can't use LinkButton because it has `display: flex`, but I need `display: contents`.
![image](https://user-images.githubusercontent.com/49731235/100441694-f3101d00-30b7-11eb-8f23-9d5398421836.png)

2020-11-27 10:54 UTC, SMPlay commented on src/components/active-sessions-warning/active-sessions-warning.module.scss
> +  &__sessions-management-button {
see above

2020-11-27 14:40 UTC, pavyarov commented on src/components/active-sessions-warning/active-sessions-warning.tsx
> +const SessionsManagementButton = activeSessionsWarning.sessionsManagementButton('span');
@SMPlay First of all u can override styles with BEM-helper. And also why `display: contents`? There are some accessibility changes at D4J?

2020-11-27 14:43 UTC, SMPlay commented on src/components/active-sessions-warning/active-sessions-warning.tsx
> +const SessionsManagementButton = activeSessionsWarning.sessionsManagementButton('span');
Bem-helper cannot override styles. Only with important

2020-11-30 09:34 UTC, RomanAchilov requested changes

2020-11-30 09:34 UTC, RomanAchilov commented on src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes-modal.module.scss
> +  &__p {
delete)

2020-11-30 14:04 UTC, IliaSolovev requested changes

2020-11-30 14:04 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/scope-summary/scope-summary.module.scss
> +    padding-bottom: 8px;
maybe: `padding: 12px 0 8px 0`?

2020-11-30 14:04 UTC, IliaSolovev commented on src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes-modal.module.scss
> +    font-size: 14px;
it looks like you can use it in block

2020-11-30 15:06 UTC, SMPlay commented on src/pages/service-group-full-page/test-to-code-plugin/finish-all-scopes-modal/finish-all-scopes-modal.module.scss
> +    font-size: 14px;
![image](https://user-images.githubusercontent.com/49731235/100626211-93737500-3336-11eb-8ddb-124ab4dbbd5c.png)
No, this button doesn't take font-size

2020-11-30 15:18 UTC, RomanAchilov approved these changes

2020-11-30 15:18 UTC, merged