EPMDJ-2832: Update service group dashboard
Drill4J/admin-ui pull request #475
Opened 2020-11-30 12:29 UTC by SMPlay

Issue: EPMDJ-2832

2020-12-01 14:46 UTC, IliaSolovev requested changes

2020-12-01 14:46 UTC, IliaSolovev commented on src/pages/service-group-full-page/dashboard/sections/coverage-section/coverage-section.module.scss
> +  display: block;
is it required?

2020-12-01 14:46 UTC, IliaSolovev commented on src/pages/service-group-full-page/dashboard/sections/coverage-section/methods-tooltip/methods-tooltip.module.scss
> +  &__covered-methods {
it is already div

2020-12-03 08:26 UTC, IliaSolovev requested changes

2020-12-03 08:26 UTC, IliaSolovev commented on src/pages/service-group-full-page/dashboard/sections/risks-section.tsx
> +              icon={<Icons.Edit height={16} width={16} viewBox="0 0 16 15" />}
Maybe `viewbox="0 0 16 16"` ? It lok strange

2020-12-03 08:26 UTC, IliaSolovev commented on src/types/service-group-summary.ts
> +import { RisksSummary } from './risks-summary';
I think that imports should be the same

2020-12-08 10:16 UTC, RomanAchilov approved these changes

2020-12-08 10:16 UTC, merged