EPMDJ-5376: Improve warning message om finish scope
Drill4J/admin-ui pull request #477
Opened 2020-12-01 10:01 UTC by SMPlay

Issue: EPMDJ-5376

2020-12-01 14:42 UTC, IliaSolovev approved these changes

2020-12-02 13:37 UTC, RomanAchilov requested changes

2020-12-02 13:37 UTC, RomanAchilov commented on src/pages/agent-full-page/coverage-plugin/scope/finish-scope-modal/finish-scope-modal.tsx
> +          {Boolean(!testsCount && testTypes.length === 0) && (
I do not understand

2020-12-02 14:39 UTC, RomanAchilov approved these changes

2020-12-02 14:40 UTC, merged