EPMDJ-5334: Improve active unicorn for new build
Drill4J/admin-ui pull request #478
Opened 2020-12-01 10:42 UTC by SMPlay

Issue: EPMDJ-5334

2020-12-01 14:42 UTC, IliaSolovev approved these changes

2020-12-02 08:30 UTC, RomanAchilov requested changes

2020-12-02 08:30 UTC, RomanAchilov commented on src/pages/agent-full-page/initial-config-controller.ts
> +    dispatch(setLoading(false));
I don't think you should expand the logic here

2020-12-02 08:30 UTC, RomanAchilov commented on src/pages/agent-full-page/initial-config-controller.ts
> +    dispatch(setLoading(false));
most likely, the problem is in the subscription.

2020-12-07 15:23 UTC, RomanAchilov approved these changes

2020-12-07 15:23 UTC, merged