EPMDJ-5593: Added t2r stubs
Drill4J/admin-ui pull request #486
Opened 2020-12-08 07:09 UTC by IliaSolovev

Issue: EPMDJ-5593

2020-12-09 09:30 UTC, SMPlay requested changes

2020-12-09 09:30 UTC, SMPlay commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.module.scss
> +  height: 100%;
\n

2020-12-09 09:30 UTC, SMPlay commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-list.tsx
> +      {testsToRun.length === 0 && <NoTestsToRunStub />}
can you use `!testsToRun.length`?

2020-12-21 17:10 UTC, RomanAchilov approved these changes

2020-12-21 17:11 UTC, merged