EPMDJ-5502: update header on tests to run page
Drill4J/admin-ui pull request #491
Opened 2020-12-09 15:17 UTC by IliaSolovev

Issue: EPMDJ-5502

2020-12-09 15:50 UTC, RomanAchilov requested changes

2020-12-09 15:50 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/saved-time-section/saved-time-section.tsx
> +          <Title>{ label }</Title>
```suggestion
          <Title>{label}</Title>
```

2020-12-09 15:50 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.module.scss
> +  &__get-suggested-tests-button {
is this necessary?

2020-12-09 15:50 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +interface TestsDuration {
move to types folder

2020-12-09 15:50 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +  autoTests: TestCoverageInfo[];
it looks like this can be generalized

2020-12-09 19:47 UTC, pavyarov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +function getTooltipMessage({
Looks rly strange, you changing render logic depending at strings.
@RomanAchilov, @RomanDavlyatshin  What do u think?

2020-12-09 19:47 UTC, pavyarov commented on src/utils/index.ts
> +export { getDuration } from './getDuration';
File name should be at kebab-case

2020-12-09 19:47 UTC, pavyarov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +              { autoTests.length && !autoTestsToRun
3 props depending at `autoTests.length` maybe put all this logic to component?

2020-12-09 20:18 UTC, IliaSolovev commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +function getTooltipMessage({
i removed this function

2020-12-18 13:31 UTC, RomanAchilov requested changes

2020-12-18 13:31 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/saved-time-section/saved-time-section.tsx
> +          position={label === 'total time saved' ? 'top-left' : 'top-center'}
delete

2020-12-18 13:31 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +  const { AUTO } = previousBuildTests
```suggestion
  const { AUTO: { total }} = useBuildVersion<TestsToRunSummary>('/build/summary/tests-to-run') || {};
```

2020-12-18 13:31 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +              message={getEstimatedTimeSavedTooltipMessage(autoTests.length, previousBuildAutoTestsCount)}
```suggestion
              message={prev ? fun() : null}
```

2020-12-21 19:04 UTC, RomanAchilov requested changes

2020-12-21 19:04 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +              message={getTotalSavedTimeTooltipMessage(Number(autoTestsToRun?.total) - Number(autoTestsToRun?.completed))}
why need Number() ?

2020-12-21 19:04 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +              message={getTotalSavedTimeTooltipMessage(Number(autoTestsToRun?.total) - Number(autoTestsToRun?.completed))}
set the default values

2020-12-21 19:04 UTC, RomanAchilov commented on src/modules/tests-to-run/tests-to-run-list/tests-to-run-header/tests-to-run-header.tsx
> +function getTotalSavedTimeTooltipMessage(autoTestsToRunCount: number) {
this is strange

2020-12-21 19:58 UTC, RomanAchilov approved these changes

2020-12-21 19:59 UTC, merged