EPMDJ-3351: Implement registration for each type of agents
Drill4J/admin-ui pull request #550
Opened 2021-02-01 10:09 UTC by RomanAchilov

Issue: EPMDJ-3351

2021-02-01 10:24 UTC, RomanAchilov commented on src/pages/agent-registration-page/agent-registration-page.tsx
> +                /^(ht|f)tp(s?)\:\/\/[0-9a-zA-Z]([-.\w]*[0-9a-zA-Z])*(:(0-9)*)*(\/?)([a-zA-Z0-9\-\.\?\,\'\/\\\+&amp;%\$#_]*)?$/,
maybe create an enumeration of available patterns?

2021-02-01 10:24 UTC, RomanAchilov commented on src/pages/settings-page/service-group-settings/service-group-general-settings-form/service-group-general-settings-form.tsx
> +                  data-test="java-general-settings-form:save-changes-button"
no need to change the data-test attributes

2021-02-09 18:01 UTC, IliaSolovev requested changes

2021-02-09 18:01 UTC, IliaSolovev commented on src/tailwind.css
> +}
add line

2021-02-10 10:24 UTC, merged