EPMDJ-6138: Add general tab to service group registration
Drill4J/admin-ui pull request #583
Opened 2021-02-18 08:13 UTC by IliaSolovev

Issue: EPMDJ-6138

2021-02-18 17:04 UTC, RomanDavlyatshin requested changes

2021-02-18 17:04 UTC, RomanDavlyatshin commented on src/pages/settings-page/service-group-settings/service-group-settings.tsx
> +          packages = [], sessionIdHeaderName = '', targetHost,
Why `targetHost` is present in the service group settings? That's weird 🤔

2021-02-18 17:04 UTC, RomanDavlyatshin commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +          if (isMounted.current) {
I don't understand - what's going on here? Can you explain me, please? 😸

2021-02-18 17:13 UTC, RomanDavlyatshin commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +          if (isMounted.current) {
@RomanAchilov that one is one you

2021-02-18 17:35 UTC, IliaSolovev commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +          await registerServiceGroup(data);
It handles in Wizard inside when onSubmit will call

2021-02-18 17:38 UTC, IliaSolovev commented on src/pages/settings-page/service-group-settings/service-group-settings.tsx
> +          packages = [], sessionIdHeaderName = '', targetHost,
I should pass it in the query payload because if BE does not receive it, the `targetHost` data will delete in db

2021-02-18 17:40 UTC, IliaSolovev commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +      {isCancelModalOpened && (
I don`t have another point, I`ll remove it because I don`t need to save some data inside the modal

2021-02-18 18:07 UTC, RomanDavlyatshin commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +          await registerServiceGroup(data);
@RomanAchilov  @IliaSolovev I suggest not resolving conversations unless you're the one who started one.
Like, I have more things to say! 😺 
So, my point is: if the `<Wizard/>` handles an error message, then it should be smarter and handle success messages as well!
I suggest adding a new prop `onSuccessMessage`:
```
 <Wizard
    onSubmit={() => {
         doStuff();
         doAnotherStuff();
         // that's it! no need to add showMessage() to report operation completion! Just pass a prop for success message text
    }}
    onSuccessMessage='Hooray, everything went fine!'
 > ...
```

2021-02-18 18:16 UTC, RomanDavlyatshin commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +      {isCancelModalOpened && (
@IliaSolovev same thing goes for the agent's registration page
Can you fix that in another PR, please?

2021-02-18 18:20 UTC, IliaSolovev commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +          await registerServiceGroup(data);
I don't mind adding it to this PR

2021-02-19 07:48 UTC, RomanDavlyatshin commented on src/pages/service-group-registration-page/service-group-registration-page.tsx
> +          await registerServiceGroup(data);
Ok, fine, for now. 😑 I guess we will discuss our branching strategy later.

2021-02-24 17:18 UTC, RomanAchilov approved these changes

2021-02-24 17:20 UTC, merged