EPMDJ-6278: Hide settings button when SG has offline or unregister agent
Drill4J/admin-ui pull request #584
Opened 2021-02-18 08:21 UTC by IliaSolovev

Issue: EPMDJ-6278

2021-02-18 15:03 UTC, pavyarov commented on src/pages/agents-page/agents-table/actions-column/actions-column.tsx
> +    <div className={`flex items-center ${status !== AGENT_STATUS.ONLINE && 'mr-8'}`}>
i don't really sure how tailwind working, but this statement `status !== AGENT_STATUS.ONLINE && 'mr-8'` will add `false` in classname?

2021-02-19 10:22 UTC, IliaSolovev commented on src/pages/agents-page/agents-table/actions-column/actions-column.tsx
> +    <div className={`flex items-center ${status !== AGENT_STATUS.ONLINE && 'mr-8'}`}>
Yes, it will add false in className in that case I need to use styled-components. But now I give margin another component

2021-02-24 16:52 UTC, RomanAchilov requested changes

2021-02-24 16:52 UTC, RomanAchilov commented on src/pages/agents-page/agents-table/actions-column/actions-column.tsx
> +  const offlineAgentsCount = agents.reduce(
.some

2021-02-24 17:14 UTC, RomanAchilov approved these changes

2021-02-24 17:14 UTC, merged