EPMDJ-6304: Move save changes button inside tabs and add unSaveChanges popup
Drill4J/admin-ui pull request #587
Opened 2021-02-24 10:18 UTC by IliaSolovev

2021-02-25 17:46 UTC, RomanAchilov requested changes

2021-02-25 17:46 UTC, RomanAchilov commented on src/pages/settings-page/agent-settings/agent-settings.tsx
> +        <Route
move above

2021-02-25 17:46 UTC, RomanAchilov commented on src/pages/settings-page/agent-settings/agent-settings.tsx
>    const [selectedTab, setSelectedTab] = useState('general');
Is this still necessary?

2021-02-25 17:46 UTC, RomanAchilov commented on src/pages/settings-page/agent-settings/agent-settings.tsx
> +  const [nextLocation, setNextLocation] = useState('');
?

2021-02-25 17:46 UTC, RomanAchilov commented on src/pages/settings-page/agent-settings/agent-settings.tsx
> +  }, [pristineSettings]);
?

2021-02-25 17:46 UTC, RomanAchilov commented on src/pages/settings-page/agent-settings/agent-settings.tsx
> +        activeTab={selectedTab}
use useParams()

2021-02-26 06:01 UTC, IliaSolovev commented on src/pages/settings-page/agent-settings/agent-settings.tsx
> +  }, [pristineSettings]);
I can set pristine to true and push when I confirm leave, but then it doesn`t work because pristine almost not set to true, and Prompt will work again

2021-02-26 16:42 UTC, RomanAchilov approved these changes

2021-02-26 16:54 UTC, merged