feat: Add auto reconnecting for socket
Drill4J/admin-ui pull request #620
Opened 2021-03-15 08:05 UTC by IliaSolovev

2021-03-15 08:19 UTC, RomanAchilov approved these changes

2021-03-15 08:19 UTC, RomanAchilov commented on src/common/connection/drill-socket.ts
> +  public autoSubscribe$: Subject<'CLOSE' | 'OPEN'>;
reconnection

2021-03-29 11:44 UTC, RomanDavlyatshin requested changes

2021-03-29 11:44 UTC, RomanDavlyatshin commented on src/common/connection/drill-socket.ts
> +        this.send(topic, 'UNSUBSCRIBE', message);
I believe that does not work as you might expect:
1. The connection is already closed, why `this.send` should work?
2.  I've noticed that these messages **are sent**, but only once the connection is reestablished. This is peculiar. Please, look into that (see first messages in the new socket after reconnect).
3. Sending the 'UNSUBSCRIBE'  message might be pointless:
  - if the backend automatically throws away subscriptions for a disconnected socket (which it should);
  - if the backend is restarted "from scratch" (thus, no previous agents exist).

2021-03-29 11:44 UTC, RomanDavlyatshin commented on src/common/connection/drill-socket.ts
> +const subscribe = (topic: string, callback: (arg: any) => void, message?: SubscriptionMessage | Record<string, unknown>) => ({
I think `subscribe` is a misleading name. It's really just a handler. Can you think of a better name?

2021-03-29 11:44 UTC, RomanDavlyatshin commented on src/common/connection/drill-socket.ts
> +        next: () => this.reconnection$.next('OPEN'),
We probably should emit `onOpenEvent`, to hide the "The backend is unavailable"  alert automatically, once the connection is reestablished.

2021-03-30 14:21 UTC, merged