EPMDJ-7214: Add pagination instead of infinite scrolling
Drill4J/admin-ui pull request #704
Opened 2021-05-21 12:58 UTC by RomanAchilov

Issue: EPMDJ-7214 EPMDJ-7234

2021-05-24 06:59 UTC, IliaSolovev requested changes

2021-05-24 06:59 UTC, IliaSolovev commented on src/components/table/table.tsx
> +            <Button primary size="small" onClick={() => gotoPage(pageCount - 1)} disabled={!canNextPage}>Last</Button>
Maybe add data-test attribute here?)

2021-05-24 06:59 UTC, IliaSolovev commented on src/components/table/table.tsx
> +  withSearchPanel = true,
Maybe you give `false` as a default value because it looks more obvious? And when you will use this component you will know that it doesn`t add smth that you are not expected

2021-05-24 07:35 UTC, RomanAchilov commented on src/components/table/table.tsx
> +            <Button primary size="small" onClick={() => gotoPage(pageCount - 1)} disabled={!canNextPage}>Last</Button>
after design

2021-05-24 07:39 UTC, RomanAchilov commented on src/components/table/table.tsx
> +  withSearchPanel = true,
I did this because we have only 2 tables where you need to disable, but all the other tables we should have with the search

2021-06-22 17:12 UTC, RomanDavlyatshin requested changes

2021-06-23 06:19 UTC, IliaSolovev requested changes

2021-06-23 06:19 UTC, IliaSolovev commented on src/components/table/table.tsx
> +              <tr {...headerGroup.getHeaderGroupProps()} tw="h-13 px-4">
I cant understand why you are use map here and in map use tr tag. I think that it should be like so
`<TableElements.TableHead>
<tr>
headerGroups.map((smth) => TableElements.TH)
</tr>
</TableElements.TableHead>
`

2021-06-23 06:19 UTC, IliaSolovev commented on src/components/table/table.tsx
> +              <tr {...headerGroup.getHeaderGroupProps()} tw="h-13 px-4">
![Screenshot 2021-06-23 090323](https://user-images.githubusercontent.com/49729985/123044103-e65f6780-d401-11eb-9761-d525c90c3c7e.png)

2021-06-23 06:19 UTC, IliaSolovev commented on src/modules/tests-to-run/tests-to-run-modal/tests-to-run-modal.tsx
> +            onChange={({ value }) => setSelectedFilter(`${value}`)}
value.toString  or String(value)?

2021-06-23 06:19 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/coverage-details/associated-test-modal/tests-list/tests-list.tsx
> +        onChange={({ value }) => setSelectedSection(`${value}`)}
value.toString or String(value)?

2021-06-23 06:19 UTC, IliaSolovev commented on src/pages/agent-full-page/coverage-plugin/risks-modal/risks-modal.tsx
> +            onChange={({ value }) => setSelectedSection(`${value}`)}
value.toString or String(value)?

2021-06-23 06:19 UTC, IliaSolovev commented on tailwind.config.js
> +      none: 'none',
Is it from the design system?

2021-06-23 11:24 UTC, RomanAchilov commented on tailwind.config.js
> +      none: 'none',
yes

2021-06-23 12:08 UTC, RomanDavlyatshin commented
As there are lots of commits, I'd rather describe my suggestions here 😃 
The file is `src/components/table/pagination.tsx ` (at the state of the last commit)
### [`createPages` function](https://github.com/Drill4J/admin-ui/blob/f2d278f3c5bb75ce8d5821d53b67c2135ede4c9e/src/components/table/pagination.tsx#L53)
1. Constant `const MAX_LEFT_OR_RIGHT_PAGES_COUNT = MAX_PAGES_RENDERED - FIRST_OR_LAST_NUMBER_WITH_ELIPSIS;` created, but it's value not used in conditionals below
2. Conditions `if (currentPage < MAX_PAGES_RENDERED - FIRST_OR_LAST_NUMBER_WITH_ELIPSIS) {` and `if (currentPage >= MAX_PAGES_RENDERED - FIRST_OR_LAST_NUMBER_WITH_ELIPSIS) {` are mutually exclusive, therefore can be rewritten as `if...else`
3. case `return createArray(1, pagesLength);` is the simplest one, therefore can be moved to the first line of function, to simplify reading
### [`pages` function](https://github.com/Drill4J/admin-ui/blob/f2d278f3c5bb75ce8d5821d53b67c2135ede4c9e/src/components/table/pagination.tsx#L123)

### Overall

The rendering logic based on `page === 'ellipsis'` looks contrived and creates/uses unnecessary string literals joggling.
I suggest to move conditions from "createPages" to the JSX itself.
With that said,  `createArray(*something*).map(page => <PageComponent *passing page props*>)` could be simplified to `renderPage(*specificPageNumber*)` and `renderPages(*fromPage*, *toPage*)` implementation

So the basic idea is:
```

const Pages = () => currentPage < MAX_PAGES_WITH_ELLIPSIS_COUNT
  ? renderPages(1, pagesLength)
  : renderPagesWithEllipsis()

const renderPages = (from, to) => createArray(from, to).map(renderPage)

const renderPage = pageNumber => (
  <PaginationElements.PageNumber active={page === currentPage} onClick={() => gotoPageByPageNumber(page)}>
    {page}
  </PaginationElements.PageNumber>
)

const renderPagesWithEllipsis = () => {
  if (currentPage < MAX_LEFT_OR_RIGHT_PAGES_COUNT) {
    return (
      <>
        { renderPages(1, MAX_LEFT_OR_RIGHT_PAGES_COUNT) }
        <Ellipsis />
        { renderPages(1, MAX_LEFT_OR_RIGHT_PAGES_COUNT) }
      </>
    )
  } else if (currentPage > pagesLength + 1 - MAX_LEFT_OR_RIGHT_PAGES_COUNT) {
    const descriptiveName = pagesLength + 1 - MAX_LEFT_OR_RIGHT_PAGES_COUNT; // duplication, but at least it's easier to grok?
    return (
      <>
        {renderPage(1)}
        <Ellipsis />
        {renderPages(descriptiveName, pagesLength)}
      </>
    )
  } else {
    return (
      <>
        {renderPage(1)}
        <Ellipsis />
        {renderPages(currentPage - 1, currentPage + 1);}
        <Ellipsis />
        {renderPage(pagesLength)}
      </>
    )
  }
}

```

2021-06-23 12:46 UTC, RomanDavlyatshin requested changes
See comment https://github.com/Drill4J/admin-ui/pull/704#issuecomment-866780514

2021-06-23 12:46 UTC, RomanDavlyatshin commented on src/components/table/pagination.tsx
> +          items={[
`[25,50,100].map(x => {label: `${x} per page`, value: x})`

2021-06-23 13:34 UTC, RomanDavlyatshin commented
@RomanAchilov  
I think you've forgot to fix that issue with `currentPage` / `pagesLength` in conditional.
[your change](https://github.com/Drill4J/admin-ui/pull/704/commits/a379f4dfc5ecdda81cac3647f2551ca3b693e58e#diff-7ae707e16fdccedfc62bf91d1aeb53abbfb26c08e999f29503d6f42ce589ac35R54) was overwritten with ctrl+c ctrl+v.

2021-06-23 13:40 UTC, RomanDavlyatshin approved these changes
👍 LGTM

2021-06-23 13:42 UTC, merged